[package]
name = "cradleos"
edition = "2024"
published-at = "0xaf2b9fca870b3e14f64f4f5935b972a39ccbc405b9d2339ccbb8ff0953fc0995"

[dependencies]
world = { local = "../world-contracts/contracts/world" }

[environments]
testnet_utopia = "4c78adac"
testnet_stillness = "4c78adac"
