import {chromium} from '/home/rawdata/.npm-global/lib/node_modules/openclaw/node_modules/playwright-core/index.mjs';
import fs from 'node:fs/promises';import assert from 'node:assert/strict';
const OUT='/home/rawdata/.openclaw-captain/workspace/research/cradleos-casino-craps-20261008',URL=process.env.QA_URL??'http://127.0.0.1:5196',K='cradleos:casino:practice:v2',tag=process.env.QA_TAG??'dev',report={checks:[],errors:[]};
const b=await chromium.launch({executablePath:'/home/rawdata/.cache/ms-playwright/chromium-1228/chrome-linux/chrome',args:['--no-sandbox']});
const c=await b.newContext({viewport:{width:390,height:1100},reducedMotion:'reduce',hasTouch:true}),p=await c.newPage();p.on('pageerror',e=>report.errors.push(e.message));
const check=x=>{report.checks.push(x);console.log(x)},read=()=>p.evaluate(k=>JSON.parse(sessionStorage.getItem(k)),K),idle=()=>p.waitForFunction(()=>!document.querySelector('.craps-roll')?.disabled||document.querySelector('.craps-roll')?.textContent.includes('Roll dice'));
async function fresh(){await p.goto(URL+'/#/casino');await p.evaluate(()=>sessionStorage.clear());await p.reload();await p.locator('.lounge-game-tile').first().waitFor();}
async function open(){await p.locator('.lounge-game-tile').filter({has:p.getByRole('heading',{name:'Frontier Craps',exact:true})}).click();}
async function inject(s){await p.evaluate(({k,s})=>sessionStorage.setItem(k,JSON.stringify(s)),{k:K,s});await p.reload();if(!s.table&&!s.hand)await p.locator('.craps-table').waitFor();else await p.locator('.lounge-hand-actions').waitFor();}
try{
 await fresh();assert.equal(await p.locator('.lounge-game-tile').count(),34);await open();await p.getByRole('button',{name:'Add Pass line 5 chips',exact:true}).click();let s=await read();assert.equal(s.balance,999500);assert.equal(s.craps.bets.pass,500);assert(await p.getByRole('button',{name:'Refill',exact:true}).isDisabled());
 await p.getByRole('button',{name:'‹ Lobby',exact:true}).click();assert(await p.locator('.craps-resume').isVisible());await p.getByRole('button',{name:'Return to table',exact:true}).click();await p.getByRole('button',{name:'Take down',exact:true}).click();await p.getByRole('button',{name:'Remove Pass line',exact:true}).click();s=await read();assert.equal(s.balance,1000000);check('34 practice games; chip placement, lobby parking/resume, refill guard and legal take-down');
 await p.getByRole('button',{name:'Place chips',exact:true}).click();await p.getByRole('button',{name:'Add Pass line 5 chips',exact:true}).click();await p.locator('.craps-roll').evaluate(e=>{e.click();e.click();e.click()});await p.waitForTimeout(300);s=await read();assert.equal(s.craps.sequence,1);assert.equal(s.craps.pending,false);assert.equal(await p.locator('.craps-dice [data-face]').count(),2);check('Actual browser RNG two-face roll; rapid triple click pays exactly one roll');
 let fixtures;
 if(URL.includes(':5196')){
  fixtures=await p.evaluate(async()=>{const {initialSession,playSession}=await import('/src/lib/casinoSessions.ts'),{changeCrapsBet:bet,rollCraps:roll,revealCraps:reveal}=await import('/src/lib/casinoCrapsSession.ts');let s=bet(initialSession(),'pass',500);s=roll(s,()=>2);const pendingPoint=s;s=reveal(s,s.craps.sequence);s=bet(s,'passOdds',2500);s=bet(s,'place8',600);s=bet(s,'hard8',100);s=bet(s,'field',500);const working=s;let i=0;const pendingWin=roll(s,()=>[2,2][i++]);const parkedBJ=playSession(s,'blackjack',100,{}, {seats:1},()=>0);return {pendingPoint,working,pendingWin,parkedBJ};});fixtures=JSON.parse(JSON.stringify(fixtures));await fs.writeFile(OUT+'/fixtures.json',JSON.stringify(fixtures));
 }else fixtures=JSON.parse(await fs.readFile(OUT+'/fixtures.json','utf8'));
 await inject(fixtures.pendingPoint);assert.equal(await p.locator('.craps-puck b').innerText(),'OFF');assert.equal(await p.locator('.craps-dice [data-face]').count(),0);assert.equal(await p.locator('.craps-receipt').count(),0);assert(await p.getByRole('button',{name:'‹ Lobby',exact:true}).isDisabled());await p.waitForTimeout(400);assert.deepEqual(await read(),fixtures.pendingPoint);await p.getByRole('button',{name:/^Reveal saved roll/}).click();await p.waitForTimeout(300);assert.equal(await p.locator('.craps-puck b').innerText(),'6');check('Pending reload hides point, dice, receipts and never advances by itself; explicit reveal only');
 await inject(fixtures.pendingWin);assert.equal(await p.locator('.craps-puck b').innerText(),'6');assert((await p.locator('.craps-bank').innerText()).includes('42'));assert((await p.locator('.lounge-balance').innerText()).includes('9,958'));assert(await p.getByRole('button',{name:'Add Field 5 chips',exact:true}).isDisabled());await p.getByRole('button',{name:/^Reveal saved roll/}).click();await p.waitForTimeout(300);s=await read();assert.equal(s.balance,fixtures.pendingWin.balance);assert.equal(s.craps.pending,false);assert.equal(await p.locator('.craps-puck b').innerText(),'OFF');check('Saved winning roll masks old bets, point and available chips until reveal; no extra credit');
 // Mutation storage failures: placement, roll, reveal keep previous durable state.
 await inject(fixtures.working);const fail=()=>p.evaluate(()=>{window.savedSet=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='cradleos:casino:practice:v2')throw new DOMException('blocked');return window.savedSet.call(this,k,v);}}),unfail=()=>p.evaluate(()=>{Storage.prototype.setItem=window.savedSet;});
 await fail();await p.getByRole('button',{name:'Add Field 5 chips',exact:true}).click();assert.deepEqual(await read(),fixtures.working);await p.locator('.craps-roll').click();assert.deepEqual(await read(),fixtures.working);await unfail();
 await inject(fixtures.pendingWin);await fail();await p.getByRole('button',{name:/^Reveal saved roll/}).click();await p.waitForTimeout(300);assert.deepEqual(await read(),fixtures.pendingWin);assert(await p.getByRole('alert').filter({hasText:'Storage unavailable'}).isVisible());await unfail();await p.getByRole('button',{name:/^Reveal saved roll/}).click();await p.waitForTimeout(300);assert.equal((await read()).balance,fixtures.pendingWin.balance);check('Placement, roll and reveal storage failures cause no partial debit, double credit or lost escrow');
 await inject(fixtures.parkedBJ);await p.locator('.craps-table').waitFor({state:'detached'});await p.locator('.lounge-hand-actions').waitFor();assert.equal((await read()).craps.bets.pass,500);check('Reload prioritizes an active blackjack hand over parked craps bets');
 await inject(fixtures.working);await p.getByRole('button',{name:'Take down',exact:true}).click();assert(await p.getByRole('button',{name:'Remove Pass line',exact:true}).isDisabled());await p.getByRole('button',{name:'Remove Pass odds',exact:true}).click();assert.equal((await read()).balance,fixtures.working.balance+2500);check('Point-lock on Pass; odds removable with exact returned escrow');
 // Time domain, responsive UI and all dice faces.
 for(const width of [1440,844,390,320]){await p.setViewportSize({width,height:width>500?1000:1200});await inject(fixtures.working);await p.screenshot({path:`${OUT}/${tag}-${width}.png`,fullPage:true});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));const boxes=await p.locator('.craps-spot').evaluateAll(es=>es.map(e=>({width:e.getBoundingClientRect().width,height:e.getBoundingClientRect().height})));report['targets'+width]=boxes;check(`${width}px table and controls fit without horizontal overflow`);}
 await p.setViewportSize({width:390,height:1100});await inject(fixtures.pendingWin);await p.emulateMedia({reducedMotion:'no-preference'});await p.getByRole('button',{name:/^Reveal saved roll/}).tap();await p.waitForTimeout(500);const trayBox=await p.locator('.craps-dice').boundingBox();assert(trayBox.y>=0 && trayBox.y+trayBox.height<=1100,JSON.stringify(trayBox));const first=await p.locator('.physical-die').first().getAttribute('style');await p.waitForTimeout(350);assert.notEqual(await p.locator('.physical-die').first().getAttribute('style'),first);assert.equal(await p.locator('.craps-puck b').innerText(),'6');await p.emulateMedia({reducedMotion:'reduce'});await p.waitForTimeout(80);const snap=await p.locator('.physical-die').first().getAttribute('style');await p.emulateMedia({reducedMotion:'no-preference'});await p.waitForTimeout(150);assert.equal(await p.locator('.physical-die').first().getAttribute('style'),snap);await p.waitForTimeout(2000);assert.equal((await read()).balance,fixtures.pendingWin.balance);check('Two tumbling dice advance over time; live reduced-motion cancellation is sticky, without ledger effects');
 await fresh();await p.getByRole('button',{name:'$EVE Testnet',exact:true}).click();assert.equal(await p.locator('.lounge-game-tile').count(),23);assert.equal(await p.getByRole('heading',{name:'Frontier Craps',exact:true}).count(),0);await p.getByRole('button',{name:'Donate $EVE',exact:true}).click();assert((await p.locator('body').innerText()).includes('Donate'));check('23 testnet games unchanged; craps is practice-only; donation route intact');
 assert.deepEqual(report.errors,[]);
}catch(e){report.failure=String(e);process.exitCode=1;console.error(e);await p.screenshot({path:`${OUT}/${tag}-failure.png`,fullPage:true}).catch(()=>{});}finally{await fs.writeFile(`${OUT}/${tag}-qa.json`,JSON.stringify(report,null,2));await b.close()}
