[package]
name = "cradleos"
edition = "2024"
published-at = "0xd98eea77615be152f02d70f50140734d7cdf18f2bfb8c02abbbb1421023841ed"

[dependencies]
world = { local = "../world-contracts/contracts/world" }

[environments]
testnet_utopia = "4c78adac"
testnet_stillness = "4c78adac"
