[package]
name = "cradleos"
edition = "2024"
published-at = "0x6d2ef8f78456d8dd03c73ead8678b83c454765a6b54b546a877a901f823a073f"

[dependencies]
world = { local = "../world-contracts/contracts/world" }

[environments]
testnet_utopia = "4c78adac"
testnet_stillness = "4c78adac"
