[package]
name = "cradleos"
edition = "2024"
published-at = "0x955d7ffb4c0bf6abc4caea3041f982ae7e9b21eb4b9c1ea500bb404609faf0ce"

[dependencies]
world = { local = "../world-contracts/contracts/world" }

[environments]
testnet_utopia = "4c78adac"
testnet_stillness = "4c78adac"
