[package]
name = "cradleos_casino"
edition = "2024"

published-at = "0x2d3d0525e80ffd9fedfcfb9e9fa83cd1c3a41c11f0ce614198cfd56d8b61628c"

[dependencies]
# Sui framework is provided implicitly by the toolchain (system dependency).
# sui::random, sui::coin, sui::balance, sui::event all live in sui-framework.

[addresses]
cradleos_casino = "0x0"

[environments]
testnet_stillness = "4c78adac"
