import {chromium} from '/home/rawdata/.npm-global/lib/node_modules/openclaw/node_modules/playwright-core/index.mjs';
import fs from 'node:fs/promises';import assert from 'node:assert/strict';
const OUT=new URL('./',import.meta.url),KEY='cradleos:casino:practice:v2';const vault=JSON.parse(await fs.readFile('/home/rawdata/.openclaw-captain/workspace/research/cradleos-casino-slot-identities-20261008/fixtures.json','utf8')).slot_vault;
const b=await chromium.launch({executablePath:'/home/rawdata/.cache/ms-playwright/chromium-1228/chrome-linux/chrome',args:['--no-sandbox']});const c=await b.newContext({viewport:{width:320,height:700},hasTouch:true,isMobile:true,reducedMotion:'no-preference'}),p=await c.newPage(),errors=[],stationRequests=[];const report={checks:[],phases:[],errors,stationRequests};
p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(/tail587192|127\.0\.0\.1:5318/.test(r.url()))stationRequests.push(r.url());});p.on('websocket',ws=>{if(/tail587192|:5318/.test(ws.url()))stationRequests.push(ws.url());});
function save(cursor){const r=structuredClone(vault);r.cursor=cursor;const round={id:1,game:r.key,stake:r.stake,payout:r.payout,values:[1,r.frames.length],label:'Saved feature'};return{version:2,balance:1000000-r.stake+r.payout,sequence:1,history:[round],hand:null,table:null,pack:{game:r.key,rounds:[round],slot:r}};}
const state=()=>p.evaluate(k=>JSON.parse(sessionStorage.getItem(k)),KEY);
async function inject(cursor){const s=save(cursor);await p.evaluate(([k,s])=>sessionStorage.setItem(k,JSON.stringify(s)),[KEY,s]);await p.reload();await p.locator('.fleet-board').waitFor();await p.locator('.fleet-board').scrollIntoViewIfNeeded();return s;}
async function snap(label,at){if(at!==undefined)await p.waitForFunction(t=>performance.now()-Number(document.querySelector('.fleet-board').dataset.motionStart)>=t,at);const x=await p.locator('.fleet-board').evaluate(e=>({elapsed:performance.now()-Number(e.dataset.motionStart),cursor:+e.dataset.cursor,raw:e.dataset.rawStopped,shutters:e.querySelectorAll('.vault-socket-shutter').length,instrument:e.querySelector('.vault-instrument')?.innerText,cells:[...e.querySelectorAll('.fleet-cell')].map(c=>({id:+c.dataset.cell,symbol:+c.dataset.symbol,classes:c.className,title:c.title,text:c.querySelector('.slot-symbol-face').textContent,faceOpacity:+getComputedStyle(c.querySelector('.slot-symbol-face')).opacity,locked:c.classList.contains('fleet-locked'),moving:c.getAnimations({subtree:true}).filter(a=>a.playState==='running').length})),overflow:document.documentElement.scrollWidth>innerWidth}));report.phases.push({label,...x});return x;}
try{
 await p.goto('http://127.0.0.1:5199/#/casino-station');await p.locator('.frontier-casino').waitFor();assert.equal(await p.locator('.casino-station').count(),0);assert.equal(await p.getByRole('button',{name:'Station ↗',exact:true}).count(),0);assert.deepEqual(stationRequests,[]);report.checks.push('retired route enters web casino without native request or station button');
 const initial=await inject(0),closed=await snap('restored-covered');report.closedCoinClasses=closed.cells.filter(x=>x.classes.includes('fleet-coin')).length;
 await p.locator('.fleet-reveal-controls button').first().tap();const scan=await snap('initial-scan-600',600);assert.equal(scan.shutters,15);assert(scan.cells.every(x=>x.title==='Unrevealed'&&!x.classes.includes('fleet-coin')));await p.locator('.fleet-board').screenshot({path:new URL('scan-320.png',OUT).pathname});
 const mid=await snap('initial-opening-1600',1600);assert(mid.cells.some(x=>x.title!=='Unrevealed')&&mid.cells.some(x=>x.title==='Unrevealed'));
 const pause=await snap('initial-readable-2900',2900);assert.equal(pause.cursor,0);assert(pause.cells.every(x=>x.title!=='Unrevealed'&&x.faceOpacity>.99));await p.waitForFunction(()=>document.querySelector('.fleet-board').dataset.cursor==='1');let s=await state();assert.equal(s.balance,initial.balance);assert.equal(s.sequence,initial.sequence);assert.deepEqual((await snap('initial-complete')).cells.map(x=>x.symbol),vault.frames[0].grid.flat());report.checks.push('initial scan / stagger / readable pause / exact endpoint / one cursor and unchanged ledger');
 const prev=await inject(1);await p.locator('.fleet-reveal-controls button').first().tap();const locks=await snap('respin-scan-600',600);assert.equal(locks.cells.filter(x=>x.locked).length,6);assert(locks.cells.filter(x=>x.locked).every(x=>x.moving===0&&x.faceOpacity===1));assert.equal(locks.shutters,9);assert.match(locks.instrument,/VAULT BREACHED/);await p.locator('.fleet-board').screenshot({path:new URL('locks-320.png',OUT).pathname});await p.waitForFunction(()=>document.querySelector('.fleet-board').dataset.cursor==='2');assert.equal((await state()).balance,prev.balance);report.checks.push('six known locks stationary; nine unresolved sockets masked; prior breach preserved');
 const reduced=await inject(1);await p.locator('.fleet-reveal-controls button').first().tap();await p.waitForTimeout(300);await p.emulateMedia({reducedMotion:'reduce'});await p.waitForFunction(()=>!document.querySelector('.vault-socket-shutter'));await p.emulateMedia({reducedMotion:'no-preference'});await p.waitForTimeout(150);assert.equal(await p.locator('.vault-socket-shutter').count(),0);await p.waitForFunction(()=>document.querySelector('.fleet-board').dataset.cursor==='2');assert.equal((await state()).balance,reduced.balance);report.checks.push('reduced→normal stays cancelled and advances once');
 await inject(1);await p.locator('.fleet-reveal-controls button').first().tap();await p.waitForTimeout(350);await p.reload();await p.locator('.fleet-board').waitFor();assert.equal((await state()).pack.slot.cursor,1);assert.equal(await p.locator('.vault-socket-shutter').count(),0);report.checks.push('mid-reveal reload retains cursor and does not autoplay');
 assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);assert.deepEqual(stationRequests,[]);report.pass=true;
}catch(e){report.pass=false;report.failure=e.stack;throw e;}
finally{await fs.writeFile(new URL('independent.json',OUT),JSON.stringify(report,null,2));console.log(JSON.stringify({pass:report.pass,checks:report.checks,closedCoinClasses:report.closedCoinClasses,failure:report.failure,errors,stationRequests},null,2));await c.close();await b.close();}
