import {chromium} from '/home/rawdata/.npm-global/lib/node_modules/openclaw/node_modules/playwright-core/index.mjs';import fs from 'node:fs/promises';import crypto from 'node:crypto';import assert from 'node:assert/strict';
const DIR=new URL('../',import.meta.url),KEY='cradleos:casino:practice:v2';const f=JSON.parse(await fs.readFile('/home/rawdata/.openclaw-captain/workspace/research/cradleos-casino-slot-identities-20261008/fixtures.json','utf8')).slot_vault;
const build=JSON.parse(await fs.readFile(new URL('build.json',DIR),'utf8'));
const b=await chromium.launch({executablePath:'/home/rawdata/.cache/ms-playwright/chromium-1228/chrome-linux/chrome',args:['--no-sandbox']});const c=await b.newContext({viewport:{width:320,height:700},hasTouch:true,isMobile:true,reducedMotion:'no-preference'}),p=await c.newPage();
const report={release:'ace82e52',source:'1eafa70',viewport:'320x700 touch normal motion',scope:'Real public app; valid frozen-engine saved Vault fixture in isolated tab storage; no app/network mocks',phases:[],stationRequests:[],pageErrors:[],consoleErrors:[],financialRequests:[]};
p.on('pageerror',e=>report.pageErrors.push(e.message));p.on('console',m=>{if(m.type()==='error')report.consoleErrors.push(m.text());});p.on('request',r=>{if(/tail587192|:5318|:10000\/join/.test(r.url()))report.stationRequests.push(r.url());if(r.method()==='POST'){try{const x=r.postDataJSON();if(/executeTransaction|signTransaction|sponsor/i.test(x.method??''))report.financialRequests.push(x.method);}catch{}}});p.on('websocket',ws=>{if(/tail587192|:5318|:10000/.test(ws.url()))report.stationRequests.push(ws.url());});
async function phase(label,at){if(at!==undefined)await p.waitForFunction(t=>performance.now()-Number(document.querySelector('.fleet-board').dataset.motionStart)>=t,at);const v=await p.locator('.fleet-board').evaluate(e=>({elapsed:performance.now()-Number(e.dataset.motionStart),cursor:+e.dataset.cursor,raw:e.dataset.rawStopped,shutters:e.querySelectorAll('.vault-socket-shutter').length,cells:[...e.querySelectorAll('.fleet-cell')].map(x=>({symbol:+x.dataset.symbol,coin:x.classList.contains('fleet-coin'),title:x.title,text:x.querySelector('.slot-symbol-face').textContent,opacity:+getComputedStyle(x.querySelector('.slot-symbol-face')).opacity}))}));report.phases.push({label,...v});return v;}
try{
 const response=await p.goto('https://cradleos.io/#/casino-station',{waitUntil:'domcontentloaded'});assert.equal(response.status(),200);await p.locator('.frontier-casino').waitFor();assert.equal(await p.locator('.casino-station').count(),0);assert.equal(await p.getByRole('button',{name:'Station ↗',exact:true}).count(),0);report.retiredRouteOpensWebCasino=true;
 report.bundleHashes={};for(const [file,expected] of Object.entries(build.artifacts)){const res=await c.request.get('https://cradleos.io'+file);assert.equal(res.status(),200);const body=await res.body(),actual=crypto.createHash('sha256').update(body).digest('hex');assert.equal(actual,expected);report.bundleHashes[file]=actual;if(file.endsWith('.js'))assert(!body.toString().includes('spark-2def.tail587192')&&!body.toString().includes('Native Carbon'));}
 const round={id:1,game:f.key,stake:f.stake,payout:f.payout,values:[1,f.frames.length],label:'Saved feature'},s={version:2,balance:1000000-f.stake+f.payout,sequence:1,history:[round],hand:null,table:null,pack:{game:f.key,rounds:[round],slot:{...structuredClone(f),cursor:0}}};await p.evaluate(([key,s])=>sessionStorage.setItem(key,JSON.stringify(s)),[KEY,s]);await p.reload();await p.locator('.fleet-board').waitFor();await p.locator('.fleet-board').scrollIntoViewIfNeeded();
 const ready=await phase('saved-ready');assert(ready.cells.every(x=>!x.coin&&x.title==='Unrevealed'));
 await p.locator('.fleet-reveal-controls button').first().tap();const closed=await phase('closed-scan-600',600);assert.equal(closed.shutters,15);assert(closed.cells.every(x=>!x.coin&&x.title==='Unrevealed'));await p.locator('.fleet-board').screenshot({path:new URL('review/live-scan-320.png',DIR).pathname});
 const mid=await phase('staggered-open-1700',1700);assert(mid.cells.some(x=>x.title==='Unrevealed')&&mid.cells.some(x=>x.title!=='Unrevealed'));
 const read=await phase('readable-pause-2900',2900);assert.equal(read.cursor,0);assert(read.cells.every(x=>x.title!=='Unrevealed'&&x.opacity>.99));await p.locator('.fleet-board').screenshot({path:new URL('review/live-readable-320.png',DIR).pathname});
 await p.waitForFunction(()=>document.querySelector('.fleet-board').dataset.cursor==='1');const end=await phase('completed');assert(end.elapsed>=3300);assert.deepEqual(end.cells.map(x=>x.symbol),f.frames[0].grid.flat());const settled=await p.evaluate(k=>JSON.parse(sessionStorage.getItem(k)),KEY);assert.equal(settled.balance,s.balance);assert.equal(settled.sequence,s.sequence);assert.equal(settled.pack.slot.cursor,1);report.unchangedBalanceAndSequence=true;report.exactEndpointAndOneCursor=true;
 await p.reload();await p.locator('.fleet-board').waitFor();assert.equal(await p.locator('.vault-socket-shutter').count(),0);assert.equal((await p.evaluate(k=>JSON.parse(sessionStorage.getItem(k)),KEY)).pack.slot.cursor,1);report.reloadStatic=true;
 report.noOverflow=await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth);assert(report.noOverflow);assert.deepEqual(report.pageErrors,[]);assert.deepEqual(report.stationRequests,[]);assert.deepEqual(report.financialRequests,[]);report.pass=true;
}catch(e){report.pass=false;report.failure=e.stack;throw e;}
finally{await fs.writeFile(new URL('live-review.json',DIR),JSON.stringify(report,null,2));console.log(JSON.stringify({pass:report.pass,bundleHashes:report.bundleHashes,phases:report.phases.map(({label,elapsed,cursor,shutters})=>({label,elapsed,cursor,shutters})),stationRequests:report.stationRequests,pageErrors:report.pageErrors,financialRequests:report.financialRequests,failure:report.failure},null,2));await c.close();await b.close();}
