import {chromium} from '/home/rawdata/.npm-global/lib/node_modules/openclaw/node_modules/playwright-core/index.mjs';
import {readFile,writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const base=process.env.QA_BASE??'http://127.0.0.1:5224',tag=process.env.QA_TAG??'preview',live=base.startsWith('https:'),out=new URL('./',import.meta.url).pathname,KEY='cradleos:casino:practice:v2',fixtures=JSON.parse(await readFile(out+'fixtures.json','utf8'));
const report={base,scope:live?'Actual app; isolated browser-local free Play Money; fresh natural RNG rounds; viewport emulation; no wallet':'Actual app; isolated browser-local free Play Money; natural draws plus explicitly fixture-seeded browser crypto for2rank draws, engine-produced saved rounds and lifecycle. No app/production RNG edits; viewport emulation; no wallet',checks:[],errors:[],assetFailures:[]};
const b=await chromium.launch({executablePath:'/home/rawdata/.cache/ms-playwright/chromium-1228/chrome-linux/chrome',args:['--no-sandbox','--no-proxy-server']});
const read=p=>p.evaluate(k=>JSON.parse(sessionStorage.getItem(k)),KEY),idle=p=>p.waitForFunction(()=>!document.querySelector('.round-active')),outcome=r=>r.values[0]===r.values[1]?'tie':r.values[0]>r.values[1]?'win':'loss';
async function init(width,reduce=false){const c=await b.newContext({viewport:{width,height:950},reducedMotion:reduce?'reduce':'no-preference'}),p=await c.newPage();p.on('pageerror',e=>report.errors.push(e.message));p.on('response',r=>{if(r.status()>=400&&r.url().includes('/casino/lai-jump/'))report.assetFailures.push(r.url())});await p.goto(base+'/#/casino');await p.locator('.lounge-game-tile').filter({hasText:'Fleet Duel'}).click();await p.locator('.fleet-duel-stage').waitFor();return{c,p};}
async function seed(p,values){await p.evaluate(values=>{const original=crypto.getRandomValues.bind(crypto),queue=[...values];crypto.getRandomValues=a=>{if(a instanceof Uint32Array&&a.length===1&&queue.length){a[0]=queue.shift();if(!queue.length)crypto.getRandomValues=original;return a}return original(a)}},values)}
async function observe(p){await p.evaluate(()=>{window.fleetFrames=[];window.fleetStop=false;function tick(){const e=document.querySelector('.fleet-duel-stage');if(e)window.fleetFrames.push({t:+e.dataset.progress,phase:e.dataset.phase,outcome:e.dataset.outcome??null,cards:[...e.querySelectorAll('.fleet-command-card')].map(n=>({rank:n.dataset.rank===undefined?null:+n.dataset.rank,aria:n.getAttribute('aria-label'),text:n.textContent,transform:n.style.transform})),ships:[...e.querySelectorAll('.fleet-ship')].map(n=>({side:+n.parentElement.dataset.side,index:+n.dataset.index,destroyed:n.dataset.destroyed==='true',transform:n.getAttribute('transform'),fragments:n.querySelectorAll('.fleet-fragment').length})),bolts:[...e.querySelectorAll('.fleet-bolt')].map(n=>({side:+n.dataset.firingSide,lethal:n.dataset.lethal==='true',path:n.getAttribute('d')})),shields:e.querySelectorAll('.fleet-shield').length,flashes:e.querySelectorAll('.fleet-destruction').length});if(!window.fleetStop)requestAnimationFrame(tick)}requestAnimationFrame(tick)});}
async function settled(p,r){const result=outcome(r);assert.equal(await p.locator('.fleet-duel-stage').getAttribute('data-outcome'),result);assert.deepEqual(await p.locator('.fleet-command-card').evaluateAll(ns=>ns.map(n=>+n.dataset.rank)),r.values);assert.equal(await p.locator('.fleet-wreck').count(),result==='tie'?0:3);assert.equal(await p.locator('.fleet-intact').count(),result==='tie'?6:3);assert.equal(await p.locator('.fleet-bolt,.fleet-shield,.fleet-destruction').count(),0);if(result==='tie')assert((await p.locator('.fleet-duel-stage>footer').innerText()).includes('½ RETURN'));assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));const geometry=await p.locator('.fleet-duel-stage').evaluate(e=>{const r=e.getBoundingClientRect();return{height:r.height,visible:Math.max(0,Math.min(innerHeight,r.bottom)-Math.max(64,r.top)),cards:[...e.querySelectorAll('.fleet-command-card')].map(n=>{const c=n.getBoundingClientRect();return{left:c.left,right:c.right,width:c.width,inside:c.left>=r.left&&c.right<=r.right}})}});assert(geometry.cards.every(c=>c.inside));assert(geometry.visible>=geometry.height*.97);return geometry;}
async function play(p,width,name,pair){if(pair)await seed(p,pair);await observe(p);await p.locator('.lounge-start').click();const committed=await read(p),r=committed.history[0],result=outcome(r);if(pair)assert.deepEqual(r.values,pair);for(const at of [.1,.32,.44,.73,.91]){await p.waitForFunction(t=>+document.querySelector('.fleet-duel-stage').dataset.progress>=t,at);await p.locator('.fleet-duel-stage').screenshot({path:out+`${tag}-${width}-${name}-${at}.png`});}await idle(p);await p.evaluate(()=>window.fleetStop=true);const frames=await p.evaluate(()=>window.fleetFrames),active=frames.filter(f=>f.t>0&&f.t<1);assert(active.length>90);assert(active.some(f=>f.bolts.length));assert(active.some(f=>f.shields));assert.notEqual(active[0].ships[0].transform,active.at(-1).ships[0].transform);for(const f of active){for(const side of [0,1]){const shown=f.t>=[.22,.3][side];assert.equal(f.cards[side].rank,shown?r.values[side]:null);if(!shown)assert.equal(f.cards[side].aria,'Unrevealed fleet card')}if(f.t<.87)assert.equal(f.outcome,null);for(const ship of f.ships){const expected=result!=='tie'&&ship.side!==(result==='win'?0:1)&&f.t>=[.7,.735,.77][ship.index];assert.equal(ship.destroyed,expected);assert.equal(ship.fragments,expected?9:0)}if(result==='tie'){assert.equal(f.flashes,0);assert(f.bolts.every(b=>!b.lethal))}}
const geometry=await settled(p,r);assert.deepEqual(await read(p),committed);report.checks.push({width,name,mode:pair?'fixture-seeded crypto through unchanged engine':'fresh natural RNG',outcome:result,values:r.values,payout:r.payout,stake:r.stake,geometry,frames:frames.length,samples:active.filter((f,i)=>i%15===0||i===active.length-1),ledgerUnchanged:true});console.log(width,name,result,'PASS');return result;}
try{
for(const width of live?[390,1440]:[320,390,1440]){const {c,p}=await init(width,width===1440);assert.equal(await p.getByRole('combobox',{name:'Game animation'}).inputValue(),'animated');assert.equal(await p.locator('[data-rank]').count(),0);if(live){const seen=new Set();for(let i=0;i<12&&(!seen.has('win')||!seen.has('loss'));i++)seen.add(await play(p,width,'natural-'+i));assert(seen.has('win')&&seen.has('loss'));}else{await play(p,width,'natural');for(const [name,s] of Object.entries(fixtures))await play(p,width,name,s.history[0].values);}await c.close();}
if(!live){for(const [name,saved] of Object.entries(fixtures)){const {c,p}=await init(320);await p.evaluate(([k,s])=>sessionStorage.setItem(k,JSON.stringify(s)),[KEY,saved]);await p.reload();await p.locator('.fleet-duel-stage').waitFor();assert.equal(await p.locator('.round-active').count(),0);await settled(p,saved.history[0]);assert.deepEqual(await read(p),saved);report.checks.push({saved:name,outcome:outcome(saved.history[0]),ledgerUnchanged:true});console.log('saved',name,'PASS');await c.close();}
for(const boundary of ['instant','system','hidden','resize','reload']){const {c,p}=await init(390,boundary==='system');if(['instant','system'].includes(boundary))await p.getByRole('combobox',{name:'Game animation'}).selectOption(boundary);await seed(p,[12,0]);await p.locator('.lounge-start').click();const committed=await read(p);await p.waitForTimeout(200);if(boundary==='hidden')await p.evaluate(()=>{Object.defineProperty(document,'hidden',{value:true,configurable:true});document.dispatchEvent(new Event('visibilitychange'))});if(boundary==='resize')await p.setViewportSize({width:320,height:950});if(boundary==='reload')await p.reload();await p.locator('.fleet-duel-stage').waitFor();if(boundary!=='resize')await settled(p,committed.history[0]);await idle(p);await settled(p,committed.history[0]);assert.deepEqual(await read(p),committed);report.checks.push({boundary,outcome:outcome(committed.history[0]),ledgerUnchanged:true});console.log(boundary,'PASS');await c.close();}}
assert.deepEqual(report.errors,[]);assert.deepEqual(report.assetFailures,[]);
}catch(e){report.failure=String(e);throw e}finally{await b.close();await writeFile(out+tag+'-browser.json',JSON.stringify(report,null,2)+'\n');}
