import {chromium} from '/home/rawdata/.npm-global/lib/node_modules/openclaw/node_modules/playwright-core/index.mjs';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const URL=process.env.QA_URL??'http://127.0.0.1:5199/',TAG=process.env.QA_TAG??'dev',OUT='/home/rawdata/.openclaw-captain/workspace/research/cradleos-casino-play-options-20261008',KEY='cradleos:casino:practice:v2';
const browser=await chromium.launch({executablePath:'/home/rawdata/.cache/ms-playwright/chromium-1228/chrome-linux/chrome',args:['--no-sandbox']});
const report={checks:[],errors:[]};const check=s=>{report.checks.push(s);console.log(s)};
const state=p=>p.evaluate(k=>JSON.parse(sessionStorage.getItem(k)),KEY);
const ready=async p=>{await p.waitForFunction(()=>!document.querySelector('.lounge-start')?.disabled&&!document.querySelector('.round-active'));};
async function game(p,name){await p.getByRole('button',{name:'‹ Lobby',exact:true}).click().catch(()=>{});await p.locator('.lounge-game-tile').filter({hasText:new RegExp(name,'i')}).click();}
try{
for(const width of [320,390,844,1440]){
 const ctx=await browser.newContext({viewport:{width,height:width===844?390:1000},reducedMotion:'reduce',hasTouch:width<1000});const p=await ctx.newPage();p.on('pageerror',e=>report.errors.push(e.message));await p.goto(URL+'#/casino');
 await game(p,'Plinko');await p.getByRole('button',{name:'10',exact:true}).last().click();await p.getByRole('button',{name:'High',exact:true}).click();await p.locator('.lounge-start').evaluate(e=>{e.click();e.click();e.click()});await ready(p);
 let s=await state(p);assert.equal(s.pack.rounds.length,10);assert.equal(s.sequence,10);assert.equal(s.pack.profile,'High');assert.equal(await p.locator('.plinko-ball').count(),10);assert.equal(s.balance,1000000-s.pack.rounds.reduce((n,r)=>n+r.stake,0)+s.pack.rounds.reduce((n,r)=>n+r.payout,0));
 await p.reload();await p.locator('.plinko-ball').first().waitFor();assert.deepEqual(await state(p),s);await p.getByRole('button',{name:'Low',exact:true}).click();assert.match(await p.locator('.lounge-plinko svg').getAttribute('aria-label'),/Low/);
 await p.screenshot({path:`${OUT}/${TAG}-${width}-plinko.png`,fullPage:true});
 await game(p,'roulette');await p.getByRole('button',{name:'Red',exact:true}).click();await p.getByRole('button',{name:'Odd',exact:true}).click();await p.getByRole('button',{name:'Bet on 0',exact:true}).click();await p.locator('.lounge-start').click();await ready(p);s=await state(p);assert.equal(s.pack.rounds.length,3);assert.equal(new Set(s.pack.rounds.map(r=>r.values[0])).size,1);const seq=s.sequence;await p.getByRole('button',{name:'Clear',exact:true}).click();await p.getByRole('button',{name:'Repeat selections',exact:true}).click();assert.equal((await state(p)).sequence,seq);assert.equal(await p.locator('.casino-wager-list button').count(),3);
 await game(p,'keno');await p.getByRole('button',{name:'＋ Ticket',exact:true}).click();await p.getByRole('button',{name:'＋ Ticket',exact:true}).click();await p.getByRole('button',{name:'＋ Ticket',exact:true}).click();assert(await p.getByRole('button',{name:'＋ Ticket',exact:true}).isDisabled());await p.getByLabel('Stake in play chips').fill('10.23');await p.getByRole('button',{name:'Apply stake above',exact:true}).click();await p.locator('.lounge-start').click();await ready(p);s=await state(p);assert.equal(s.pack.rounds.length,4);assert.equal(s.pack.rounds[3].stake,1023);assert(s.pack.rounds.every(r=>JSON.stringify(r.values.slice(-10))===JSON.stringify(s.pack.rounds[0].values.slice(-10))));await p.reload();await p.locator('.casino-keno-stage').waitFor();assert.deepEqual(await state(p),s);
 await game(p,'scratch');await p.getByRole('button',{name:'5',exact:true}).click();await p.locator('.lounge-start').click();await ready(p);s=await state(p);assert.equal(s.pack.rounds.length,5);assert.equal(await p.locator('.casino-scratch-ticket').count(),5);await p.reload();await p.locator('.casino-scratch-ticket').first().waitFor();assert.deepEqual(await state(p),s);
 await game(p,'blackjack');await p.getByRole('button',{name:'3',exact:true}).click();await p.locator('.lounge-start').click();await ready(p);s=await state(p);if(s.table){assert(await p.getByRole('button',{name:'Donate $EVE',exact:true}).isDisabled());assert(await p.getByRole('button',{name:'$EVE Testnet',exact:true}).isDisabled());await p.reload();await p.locator('.active-seat').waitFor();assert.deepEqual(await state(p),s);await p.screenshot({path:`${OUT}/${TAG}-${width}-blackjack.png`,fullPage:true});}
 let steps=0;while((await state(p)).table){await p.getByRole('button',{name:'Stand',exact:true}).click();await ready(p);assert(++steps<8);}s=await state(p);assert.equal(s.pack.table.seats,3);assert.equal(s.pack.rounds.length,3);
 assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 await p.getByRole('button',{name:'Donate $EVE',exact:true}).click();await p.getByRole('heading',{name:'Seed the house'}).waitFor();assert(await p.getByRole('button',{name:'Donate $EVE',exact:true}).isDisabled());
 await p.getByRole('button',{name:'Back to casino',exact:false}).click();await p.getByRole('button',{name:'$EVE Testnet',exact:true}).click();await p.locator('.lounge-game-tile').first().click();assert(await p.locator('.lounge-chain-table button:disabled').count()>0);
 check(`${width}px: all five games, aggregate stake, triple-click one pack, reload continuity, receipt profiles, shared draws, blackjack locks, donation and testnet boundaries`);await ctx.close();
}
// Normal-motion pack: the final ball must complete before unlocking controls.
{
 const ctx=await browser.newContext({viewport:{width:390,height:1000},reducedMotion:'no-preference'}),p=await ctx.newPage();await p.goto(URL+'#/casino');await game(p,'Plinko');await p.getByRole('button',{name:'10',exact:true}).last().click();await p.locator('.lounge-start').click();await p.waitForTimeout(2450);assert(await p.locator('.lounge-start').isDisabled());assert.equal(await p.locator('.plinko-ball').count(),10);await ready(p);assert.equal(await p.locator('.lounge-plinko svg').getAttribute('data-landed'),'true');
 await game(p,'scratch');await p.getByRole('button',{name:'3',exact:true}).click();await p.locator('.lounge-start').click();await ready(p);const before=await state(p);const canvas=p.locator('.casino-scratch-area canvas').first();await canvas.scrollIntoViewIfNeeded();const b=await canvas.boundingBox();await p.mouse.move(b.x+10,b.y+10);await p.mouse.down();for(let y=20;y<b.height-5;y+=18){for(const x of [12,b.width-12])await p.mouse.move(b.x+x,b.y+y,{steps:12});}await p.mouse.up();await p.getByRole('button',{name:'Reveal all tickets',exact:true}).click();assert.equal(await p.locator('.casino-scratch-area canvas').count(),0);assert.deepEqual(await state(p),before);
 // A blocked storage commit must leave the same balance and receipt.
 await game(p,'Plinko');await p.evaluate(()=>{window.__oldSet=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='cradleos:casino:practice:v2')throw new DOMException('blocked');return window.__oldSet.call(this,k,v)}});await p.locator('.lounge-start').click();await p.getByRole('alert').filter({hasText:'storage is unavailable'}).waitFor();assert.deepEqual(await state(p),before);
 check('Normal motion: staggered 10-ball duration, pointer scratch/reveal without ledger mutations, failed storage commit no debit');await ctx.close();
}
assert.deepEqual(report.errors,[]);await fs.writeFile(`${OUT}/${TAG}-qa.json`,JSON.stringify(report,null,2));
}finally{await browser.close();}
