import {chromium} from '/home/rawdata/.npm-global/lib/node_modules/openclaw/node_modules/playwright-core/index.mjs';
import {readFile,writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const base=process.env.QA_BASE??'http://127.0.0.1:5222',tag=process.env.QA_TAG??'preview',live=base.startsWith('https:'),out=new URL('./',import.meta.url).pathname,KEY='cradleos:casino:practice:v2',fixtures=JSON.parse(await readFile(out+'fixtures.json','utf8'));
const report={base,scope:live?'Actual app; isolated browser-local free Play Money; fresh natural RNG only; viewport emulation; no wallet':'Actual app; isolated browser-local free Play Money; natural RNG, engine-produced saved edges and lifecycle; viewport emulation; no wallet',checks:[],errors:[]};
const b=await chromium.launch({executablePath:'/home/rawdata/.cache/ms-playwright/chromium-1228/chrome-linux/chrome',args:['--no-sandbox','--no-proxy-server']});
const read=p=>p.evaluate(k=>JSON.parse(sessionStorage.getItem(k)),KEY),idle=p=>p.waitForFunction(()=>!document.querySelector('.round-active'));
async function init(width,reduce=false){const c=await b.newContext({viewport:{width,height:950},reducedMotion:reduce?'reduce':'no-preference'}),p=await c.newPage();p.on('pageerror',e=>report.errors.push(e.message));await p.goto(base+'/#/casino');await p.locator('.lounge-game-tile').filter({hasText:'Probability Drive'}).click();await p.locator('.probability-stage').waitFor();return{c,p};}
async function sample(p,watch=false){return p.evaluate(watch=>{window.probSample=()=>{const e=document.querySelector('.probability-stage'),rail=e.querySelector('.probability-rail').getBoundingClientRect(),needle=e.querySelector('[data-roll]'),center=n=>{const r=n.getBoundingClientRect();return r.left+r.width/2},target=e.querySelector('[data-threshold]');return{t:+e.dataset.progress,landed:e.dataset.landed==='true',busy:!!document.querySelector('.round-active'),number:+e.querySelector('strong').textContent,roll:needle?+needle.dataset.roll:null,position:needle?+needle.dataset.position:null,needle:needle?center(needle):null,rail:{left:rail.left,width:rail.width},ticks:[...e.querySelectorAll('[data-tick]')].map(n=>({v:+n.dataset.tick,x:center(n.querySelector('i'))})),target:target?{v:+target.dataset.threshold,x:center(target)}:null}};if(watch){window.probFrames=[];window.probStop=false;function tick(){window.probFrames.push(window.probSample());if(!window.probStop)requestAnimationFrame(tick)}requestAnimationFrame(tick)}return window.probSample()},watch)}
function geometry(f){const x=v=>f.rail.left+f.rail.width*(v-1)/99;for(const tick of f.ticks)assert(Math.abs(tick.x-x(tick.v))<.65,`tick ${tick.v}: ${tick.x-x(tick.v)}`);if(f.target)assert(Math.abs(f.target.x-x(f.target.v))<.65,'threshold');if(f.roll!==null){assert.equal(f.number,f.roll);assert.equal(f.roll,Math.round(f.position));assert(Math.abs(f.needle-x(f.position))<.65,'needle');assert(f.position>=1&&f.position<=100)}}
async function framing(p){assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));return p.locator('.probability-stage').evaluate(e=>{const r=e.getBoundingClientRect();return{height:r.height,visible:Math.max(0,Math.min(innerHeight,r.bottom)-Math.max(64,r.top))}})}
try{
for(const width of live?[390,1440]:[320,390,1440]){const {c,p}=await init(width,width===1440);assert.equal(await p.getByRole('combobox',{name:'Game animation'}).inputValue(),'animated');const before=await sample(p);assert.equal(before.roll,null);geometry(before);await sample(p,true);await p.locator('.lounge-start').click();const committed=await read(p),result=committed.history[0].values[0];await p.waitForFunction(()=>+document.querySelector('.probability-stage').dataset.progress>.45);await p.locator('.probability-stage').screenshot({path:out+`${tag}-${width}-sweep.png`});await p.waitForFunction(()=>document.querySelector('.probability-stage').dataset.landed==='true');const landing=await sample(p);assert(landing.t<1);assert.equal(landing.position,result);assert(landing.busy);await p.locator('.probability-stage').screenshot({path:out+`${tag}-${width}-landed.png`});await idle(p);await p.evaluate(()=>window.probStop=true);const frames=await p.evaluate(()=>window.probFrames),moving=frames.filter(f=>f.t>0&&f.t<.92),hold=frames.filter(f=>f.t>=.92&&f.t<1);assert(moving.length>25);assert(new Set(moving.map(f=>f.position)).size>25);assert(hold.length>3);for(const f of frames)geometry(f);assert(hold.every(f=>f.position===result&&f.number===result&&f.landed));const final=await sample(p);assert.equal(final.position,result);assert.equal(final.number,result);geometry(final);assert.deepEqual(await read(p),committed);const frame=await framing(p);assert(frame.visible>=frame.height*.97);report.checks.push({width,result,frameCount:frames.length,holdFrames:hold.length,landing,final,framing:frame,samples:frames.filter((f,i)=>i%12===0||i===frames.length-1),ledgerUnchanged:true});console.log(width,result,'PASS');await c.close();}
if(!live){for(const width of [320,1440])for(const [roll,saved] of Object.entries(fixtures)){const {c,p}=await init(width);await p.evaluate(([k,s])=>sessionStorage.setItem(k,JSON.stringify(s)),[KEY,saved]);await p.reload();await p.locator('.probability-stage').waitFor();const final=await sample(p);assert.equal(final.t,1);assert(final.landed);assert(!final.busy);assert.equal(final.number,+roll);assert.equal(final.position,+roll);geometry(final);assert.deepEqual(await read(p),saved);await framing(p);await p.locator('.probability-stage').screenshot({path:out+`${tag}-${width}-saved-${roll}.png`});report.checks.push({width,savedRoll:+roll,final,ledgerUnchanged:true});console.log(width,'saved',roll,'PASS');await c.close();}
for(const boundary of ['instant','system','hidden','resize','reload']){const {c,p}=await init(390,boundary==='system');if(['instant','system'].includes(boundary))await p.getByRole('combobox',{name:'Game animation'}).selectOption(boundary);await p.locator('.lounge-start').click();const committed=await read(p),result=committed.history[0].values[0];await p.waitForTimeout(200);if(boundary==='hidden')await p.evaluate(()=>{Object.defineProperty(document,'hidden',{value:true,configurable:true});document.dispatchEvent(new Event('visibilitychange'))});if(boundary==='resize')await p.setViewportSize({width:320,height:950});if(boundary==='reload')await p.reload();if(boundary!=='resize'){await p.locator('.probability-stage').waitFor();assert.equal(await p.locator('.probability-stage').getAttribute('data-landed'),'true')}await idle(p);const final=await sample(p);assert.equal(final.position,result);assert.equal(final.number,result);geometry(final);assert.deepEqual(await read(p),committed);report.checks.push({boundary,result,final,ledgerUnchanged:true});console.log(boundary,'PASS');await c.close();}}
assert.deepEqual(report.errors,[]);
}catch(e){report.failure=String(e);throw e}finally{await b.close();await writeFile(out+tag+'-browser.json',JSON.stringify(report,null,2)+'\n');}
