/**
 * GameDataPanel — Sanctuary game-data viewport for CradleOS.
 *
 * Renders extracted human-readable content from the EVE Frontier client
 * static data + a placeholder slot for the 3D mesh viewer (pending CMF
 * format port from carbonengine/mesh).
 *
 * Data sources (public/data/, generated by
 * `frontier/datamine/sanctuary/extract_for_dapp.py`):
 *   - game-data-meta.json          (build version, counts, extraction date)
 *   - game-data-strings-index.json (~216k display strings, ~6 MB / ~2 MB gz)
 *   - game-data-catalogue.json     (curated typeID groups: structures,
 *                                   turrets, shells, refuge, ecosystem)
 *   - game-data-cycle-deltas.json  (new/changed staticdata vs Cycle 5)
 *   - game-data-eventtypes.json    (Cycle 5 event types carry-over)
 *
 * Each subview lazy-loads its data on first activation so the initial
 * panel render is cheap.
 */
import { useEffect, useMemo, useRef, useState } from "react";

const ACCENT = "#FF4700";
const ACCENT_BLUE = "#64b4ff";
const ACCENT_AMBER = "#ffc850";
const ACCENT_GREEN = "#44ffaa";
const MUTED = "rgba(175,175,155,0.55)";
const TEXT = "#e0e0d0";

const BASE = `${import.meta.env.BASE_URL ?? "/"}data`;

// ── Types ──────────────────────────────────────────────────────────────────

type Meta = {
  cycle: string;
  version: string;
  build: string;
  extracted_at: string;
  counts: {
    strings_total: number;
    strings_index: number;
    catalogue_rows: number;
    deltas_added: number;
    deltas_changed: number;
    deltas_removed: number;
  };
};

type CatalogueRow = {
  typeID: number;
  label: string;
  text: string | null;
  desc: string | null;
  group: string;
};

type CatalogueDoc = Record<string, CatalogueRow[] | Array<{ typeID: number; text: string; desc: string | null }>>;

type CycleDeltas = {
  added: string[];
  changed: string[];
  removed: string[];
};

type EventType = { eventTypeName: string };

// ── Hooks ───────────────────────────────────────────────────────────────────

function useJson<T>(url: string, enabled: boolean): { data: T | null; loading: boolean; error: string | null } {
  const [data, setData] = useState<T | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!enabled || data) return;
    let cancelled = false;
    setLoading(true);
    setError(null);
    fetch(url)
      .then(r => { if (!r.ok) throw new Error(`HTTP ${r.status}`); return r.json(); })
      .then(j => { if (!cancelled) setData(j as T); })
      .catch(e => { if (!cancelled) setError(String(e.message ?? e)); })
      .finally(() => { if (!cancelled) setLoading(false); });
    return () => { cancelled = true; };
  }, [url, enabled, data]);

  return { data, loading, error };
}

// ── Subcomponents ──────────────────────────────────────────────────────────

function Header({ meta }: { meta: Meta | null }) {
  return (
    <div style={{
      display: "flex", alignItems: "center", gap: 12, marginBottom: 16, flexWrap: "wrap",
    }}>
      <span style={{ color: ACCENT, fontWeight: 700, fontSize: 16, letterSpacing: "0.06em" }}>
        ◇ GAME DATA VIEWPORT
      </span>
      {meta && (
        <span style={{
          fontSize: 10, color: MUTED, fontFamily: "monospace",
          background: "rgba(255,71,0,0.06)", border: "1px solid rgba(255,71,0,0.15)",
          padding: "2px 8px", letterSpacing: "0.1em",
        }}>
          {meta.cycle.toUpperCase()} · {meta.version} · build {meta.build}
        </span>
      )}
    </div>
  );
}

function TabStrip({ active, onChange }: { active: SubTab; onChange: (t: SubTab) => void }) {
  const TABS: Array<[SubTab, string]> = [
    ["catalogue", "▣ CATALOGUE"],
    ["strings",   "≣ STRINGS"],
    ["deltas",    "Δ CYCLE DELTAS"],
    ["events",    "✦ EVENT TYPES"],
    ["viewport3d", "◯ 3D PREVIEW"],
  ];
  return (
    <div style={{ display: "flex", borderBottom: "2px solid rgba(255,71,0,0.2)", marginBottom: 12, flexWrap: "wrap" }}>
      {TABS.map(([t, label]) => (
        <button key={t} onClick={() => onChange(t)} style={{
          fontFamily: "inherit", fontSize: 11, fontWeight: 700, letterSpacing: "0.1em",
          padding: "7px 14px", border: "none", cursor: "pointer",
          background: active === t ? "rgba(255,71,0,0.12)" : "transparent",
          color: active === t ? ACCENT : "rgba(255,255,255,0.35)",
          borderBottom: active === t ? `2px solid ${ACCENT}` : "2px solid transparent",
          marginBottom: -2,
        }}>{label}</button>
      ))}
    </div>
  );
}

type SubTab = "catalogue" | "strings" | "deltas" | "events" | "viewport3d";

// ── Catalogue subview ──────────────────────────────────────────────────────

const GROUP_META: Record<string, { label: string; accent: string; emoji: string }> = {
  structures:               { label: "Structures",        accent: ACCENT,       emoji: "▣" },
  turrets:                  { label: "Turrets",           accent: ACCENT_AMBER, emoji: "⊞" },
  shells_and_nursery:       { label: "Shell System",      accent: ACCENT_GREEN, emoji: "◉" },
  refuge:                   { label: "Refuge",            accent: ACCENT_BLUE,  emoji: "✦" },
  ecosystem_dungeons:       { label: "Ecosystem",         accent: ACCENT_GREEN, emoji: "≣" },
  sanctuary_new_structures: { label: "New This Cycle",    accent: ACCENT,       emoji: "★" },
  kitbash_strings:          { label: "Kitbash (preview)", accent: ACCENT_AMBER, emoji: "⚙" },
};

function CatalogueView() {
  const { data, loading, error } = useJson<CatalogueDoc>(`${BASE}/game-data-catalogue.json`, true);
  if (loading) return <Loading label="Loading catalogue…" />;
  if (error)   return <ErrorBox text={`Could not load catalogue: ${error}`} />;
  if (!data)   return null;

  const groups = Object.keys(data).filter(k => GROUP_META[k]);

  return (
    <div style={{ display: "grid", gap: 14 }}>
      {groups.map(key => {
        const rows = data[key] as Array<CatalogueRow | { typeID: number; text: string; desc: string | null }>;
        const meta = GROUP_META[key];
        return (
          <section key={key}>
            <div style={{
              display: "flex", alignItems: "baseline", gap: 8, marginBottom: 6,
            }}>
              <span style={{ color: meta.accent, fontWeight: 700, letterSpacing: "0.12em", fontSize: 12 }}>
                {meta.emoji} {meta.label.toUpperCase()}
              </span>
              <span style={{ fontSize: 10, color: MUTED }}>
                {rows.length} entries
              </span>
            </div>
            <div style={{
              display: "grid", gap: 4,
              gridTemplateColumns: "repeat(auto-fill, minmax(280px, 1fr))",
            }}>
              {rows.map((r, i) => (
                <CatalogueCard key={`${key}-${i}`} row={r} accent={meta.accent} />
              ))}
            </div>
          </section>
        );
      })}
    </div>
  );
}

function CatalogueCard({ row, accent }: {
  row: CatalogueRow | { typeID: number; text: string; desc: string | null };
  accent: string;
}) {
  const label = "label" in row ? row.label : row.text;
  const text = row.text;
  const desc = row.desc;
  return (
    <div style={{
      background: "rgba(255,255,255,0.02)",
      border: `1px solid ${accent}33`,
      borderLeft: `2px solid ${accent}`,
      borderRadius: 2,
      padding: "8px 10px",
      fontSize: 11,
    }}>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline", gap: 8 }}>
        <span style={{ color: TEXT, fontWeight: 700 }}>{label}</span>
        <span style={{ fontSize: 9, color: MUTED, fontFamily: "monospace" }}>#{row.typeID}</span>
      </div>
      {text && text !== label && (
        <div style={{ marginTop: 2, color: "rgba(220,220,200,0.7)", fontSize: 10 }}>{text}</div>
      )}
      {desc && (
        <div style={{ marginTop: 4, color: MUTED, fontSize: 10, lineHeight: 1.4 }}>{desc}</div>
      )}
    </div>
  );
}

// ── Strings subview ───────────────────────────────────────────────────────

function StringsView() {
  const { data, loading, error } = useJson<Record<string, string>>(`${BASE}/game-data-strings-index.json`, true);
  const [q, setQ] = useState("");
  const [limit, setLimit] = useState(100);

  const filtered = useMemo(() => {
    if (!data) return [] as Array<[string, string]>;
    const qLc = q.trim().toLowerCase();
    if (qLc.length === 0) return Object.entries(data).slice(0, limit);
    if (qLc.length < 2) return [];
    const out: Array<[string, string]> = [];
    for (const [tid, text] of Object.entries(data)) {
      // typeID exact match or substring match on text
      if (tid === qLc || text.toLowerCase().includes(qLc)) {
        out.push([tid, text]);
        if (out.length >= limit) break;
      }
    }
    return out;
  }, [data, q, limit]);

  if (loading) return <Loading label="Loading 216,785-entry strings index…" />;
  if (error)   return <ErrorBox text={`Could not load strings: ${error}`} />;

  return (
    <div>
      <div style={{ display: "flex", gap: 8, marginBottom: 12, alignItems: "center" }}>
        <input
          value={q}
          onChange={e => setQ(e.target.value)}
          placeholder="search game text or typeID…"
          style={{
            flex: 1, minWidth: 200,
            background: "rgba(255,255,255,0.04)",
            border: "1px solid rgba(255,255,255,0.12)",
            color: TEXT, fontSize: 12, padding: "6px 12px", outline: "none",
            borderRadius: 2,
          }}
        />
        <select
          value={limit}
          onChange={e => setLimit(Number(e.target.value))}
          style={{
            background: "rgba(255,255,255,0.04)",
            border: "1px solid rgba(255,255,255,0.12)",
            color: TEXT, fontSize: 11, padding: "5px 8px",
          }}
        >
          <option value={50}>50 results</option>
          <option value={100}>100 results</option>
          <option value={500}>500 results</option>
        </select>
      </div>
      <div style={{ fontSize: 10, color: MUTED, marginBottom: 8 }}>
        {data && (
          q.trim().length === 0
            ? <>Showing first {Math.min(limit, Object.keys(data).length)} of {Object.keys(data).length.toLocaleString()} display strings. Type to search.</>
            : <>{filtered.length} matches{filtered.length >= limit ? " (capped — narrow your query)" : ""}.</>
        )}
      </div>
      <div style={{ display: "grid", gap: 2 }}>
        {filtered.map(([tid, text]) => (
          <div key={tid} style={{
            display: "grid", gridTemplateColumns: "84px 1fr",
            gap: 8, padding: "4px 8px",
            fontSize: 11,
            background: "rgba(255,255,255,0.02)",
            borderLeft: "2px solid rgba(255,71,0,0.25)",
          }}>
            <span style={{ color: MUTED, fontFamily: "monospace", fontSize: 10 }}>#{tid}</span>
            <span style={{ color: TEXT }}>{text}</span>
          </div>
        ))}
        {q.trim().length === 1 && (
          <div style={{ color: MUTED, fontSize: 11, padding: 12 }}>Type at least 2 characters to search.</div>
        )}
      </div>
    </div>
  );
}

// ── Cycle deltas subview ──────────────────────────────────────────────────

function DeltasView() {
  const { data, loading, error } = useJson<CycleDeltas>(`${BASE}/game-data-cycle-deltas.json`, true);
  if (loading) return <Loading label="Loading cycle deltas…" />;
  if (error)   return <ErrorBox text={`Could not load deltas: ${error}`} />;
  if (!data)   return null;

  const sections: Array<[string, string[], string, string]> = [
    ["NEW IN SANCTUARY", data.added, ACCENT_GREEN, "+"],
    ["CONTENT ROTATED", data.changed, ACCENT_AMBER, "Δ"],
    ["REMOVED FROM CYCLE 5", data.removed, "#ff5070", "−"],
  ];

  return (
    <div style={{ display: "grid", gap: 14 }}>
      {sections.map(([label, items, accent, glyph]) => (
        <section key={label}>
          <div style={{ color: accent, fontWeight: 700, fontSize: 12, letterSpacing: "0.12em", marginBottom: 6 }}>
            {glyph}  {label}  ({items.length})
          </div>
          {items.length === 0 ? (
            <div style={{ color: MUTED, fontSize: 11 }}>—</div>
          ) : (
            <div style={{ display: "grid", gap: 2 }}>
              {items.map(p => (
                <div key={p} style={{
                  fontFamily: "monospace", fontSize: 11,
                  color: TEXT,
                  background: "rgba(255,255,255,0.02)",
                  borderLeft: `2px solid ${accent}`,
                  padding: "3px 8px",
                }}>{p}</div>
              ))}
            </div>
          )}
        </section>
      ))}
    </div>
  );
}

// ── Event types subview ──────────────────────────────────────────────────

function EventTypesView() {
  const { data, loading, error } = useJson<Record<string, EventType>>(`${BASE}/game-data-eventtypes.json`, true);
  if (loading) return <Loading label="Loading event types…" />;
  if (error)   return <ErrorBox text={`Could not load events: ${error}`} />;
  if (!data)   return null;
  const rows = Object.entries(data);
  return (
    <div style={{ display: "grid", gap: 2 }}>
      <div style={{ fontSize: 10, color: MUTED, marginBottom: 6 }}>
        {rows.length} canonical event types (carries forward from Cycle 5).
      </div>
      {rows.map(([id, e]) => (
        <div key={id} style={{
          display: "grid", gridTemplateColumns: "60px 1fr",
          fontSize: 11, padding: "3px 8px",
          background: "rgba(255,255,255,0.02)",
          borderLeft: `2px solid ${ACCENT}55`,
        }}>
          <span style={{ color: MUTED, fontFamily: "monospace" }}>#{id}</span>
          <span style={{ color: TEXT }}>{e.eventTypeName || "(unnamed)"}</span>
        </div>
      ))}
    </div>
  );
}

// ── 3D viewport (placeholder for now) ─────────────────────────────────────

function Viewport3D() {
  const canvasRef = useRef<HTMLDivElement | null>(null);

  // Draw a slowly-rotating wireframe placeholder so the panel feels live.
  useEffect(() => {
    const el = canvasRef.current;
    if (!el) return;
    let angle = 0;
    let raf = 0;
    const tick = () => {
      angle = (angle + 0.4) % 360;
      el.style.transform = `perspective(420px) rotateY(${angle}deg) rotateX(${Math.sin(angle * Math.PI / 180) * 12}deg)`;
      raf = requestAnimationFrame(tick);
    };
    raf = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(raf);
  }, []);

  return (
    <div>
      <div style={{
        background: "rgba(255,255,255,0.02)",
        border: "1px solid rgba(255,71,0,0.18)",
        borderRadius: 2,
        padding: 20,
        marginBottom: 14,
        minHeight: 280,
        display: "grid", placeItems: "center",
        position: "relative", overflow: "hidden",
      }}>
        {/* Wireframe placeholder shape */}
        <div ref={canvasRef} style={{
          width: 160, height: 160,
          border: `1.5px solid ${ACCENT}`,
          borderTopColor: ACCENT_BLUE,
          borderRightColor: ACCENT_AMBER,
          borderBottomColor: ACCENT_GREEN,
          borderRadius: "50%",
          boxShadow: `0 0 60px ${ACCENT}33, inset 0 0 30px ${ACCENT}22`,
          transformStyle: "preserve-3d",
          position: "relative",
        }}>
          <div style={{
            position: "absolute", top: "50%", left: "50%",
            transform: "translate(-50%,-50%) rotateX(90deg)",
            width: 160, height: 160,
            border: `1.5px solid ${ACCENT_BLUE}`,
            borderRadius: "50%",
          }} />
          <div style={{
            position: "absolute", top: "50%", left: "50%",
            transform: "translate(-50%,-50%) rotateY(90deg)",
            width: 160, height: 160,
            border: `1.5px solid ${ACCENT_GREEN}`,
            borderRadius: "50%",
          }} />
        </div>
      </div>
      <div style={{ fontSize: 11, color: TEXT, lineHeight: 1.6 }}>
        <div style={{ color: ACCENT, fontWeight: 700, marginBottom: 6 }}>◇ 3D Mesh Viewport — roadmap</div>
        <p style={{ margin: "0 0 6px 0", color: "rgba(220,220,200,0.85)" }}>
          The static client ships ships, structures, and turrets as <code style={{ color: ACCENT_AMBER }}>.cmf</code> meshes
          (Carbon Mesh Format), decoded by the open-sourced{" "}
          <a href="https://github.com/carbonengine/mesh" target="_blank" rel="noreferrer"
             style={{ color: ACCENT_BLUE }}>carbonengine/mesh</a> C++ library.
          A WASM build or a TypeScript port is required to render them in-browser; both are tractable
          but not in scope for tonight's drop.
        </p>
        <p style={{ margin: "0 0 6px 0", color: MUTED }}>
          Until that's wired up, this slot showcases that the data flow is in place — the same
          extractor pipeline that produced the catalogue and strings indices is parked at
          <code style={{ color: ACCENT_AMBER }}> frontier/datamine/sanctuary/extract_for_dapp.py</code>{" "}
          and ready to emit mesh metadata as soon as the loader lands.
        </p>
        <p style={{ margin: 0, color: MUTED, fontSize: 10 }}>
          Next iteration: WASM <code>carbonengine/mesh</code> + three.js renderer, then progressively
          load Refuge / Nursery / RAINMAKER / HARBINGER hulls into a model browser.
        </p>
      </div>
    </div>
  );
}

// ── Shared chrome ─────────────────────────────────────────────────────────

function Loading({ label }: { label: string }) {
  return <div style={{ color: ACCENT_AMBER, fontSize: 11, padding: 12 }}>● {label}</div>;
}

function ErrorBox({ text }: { text: string }) {
  return (
    <div style={{
      color: "#ff5070", fontSize: 11, padding: 12,
      background: "rgba(255,80,112,0.06)", border: "1px solid rgba(255,80,112,0.25)",
    }}>
      ⚠ {text}
    </div>
  );
}

// ── Top-level panel ───────────────────────────────────────────────────────

export function GameDataPanel() {
  const [tab, setTab] = useState<SubTab>("catalogue");
  const { data: meta } = useJson<Meta>(`${BASE}/game-data-meta.json`, true);

  return (
    <div style={{ padding: 20, maxWidth: 1000, margin: "0 auto" }}>
      <Header meta={meta} />
      <TabStrip active={tab} onChange={setTab} />
      {tab === "catalogue"  && <CatalogueView />}
      {tab === "strings"    && <StringsView />}
      {tab === "deltas"     && <DeltasView />}
      {tab === "events"     && <EventTypesView />}
      {tab === "viewport3d" && <Viewport3D />}

      {meta && (
        <div style={{
          marginTop: 18, paddingTop: 10,
          borderTop: "1px solid rgba(255,255,255,0.06)",
          fontSize: 9, color: MUTED, fontFamily: "monospace",
        }}>
          extracted {meta.extracted_at} · strings {meta.counts.strings_index.toLocaleString()} indexed of {meta.counts.strings_total.toLocaleString()} total · catalogue {meta.counts.catalogue_rows} rows · deltas +{meta.counts.deltas_added} Δ{meta.counts.deltas_changed} −{meta.counts.deltas_removed}
        </div>
      )}
    </div>
  );
}
