/**
 * GameDataPanel — Sanctuary game-data viewport for CradleOS.
 *
 * Renders extracted human-readable content from the EVE Frontier client
 * static data + a placeholder slot for the 3D mesh viewer (pending CMF
 * format port from carbonengine/mesh).
 *
 * Data sources (public/data/, generated by
 * `frontier/datamine/sanctuary/extract_for_dapp.py`):
 *   - game-data-meta.json          (build version, counts, extraction date)
 *   - game-data-strings-index.json (~216k display strings, ~6 MB / ~2 MB gz)
 *   - game-data-catalogue.json     (curated typeID groups: structures,
 *                                   turrets, shells, refuge, ecosystem)
 *   - game-data-cycle-deltas.json  (new/changed staticdata vs Cycle 5)
 *   - game-data-eventtypes.json    (Cycle 5 event types carry-over)
 *
 * Each subview lazy-loads its data on first activation so the initial
 * panel render is cheap.
 */
import { useEffect, useMemo, useRef, useState } from "react";
import * as THREE from "three";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader.js";

const ACCENT = "#FF4700";
const ACCENT_BLUE = "#64b4ff";
const ACCENT_AMBER = "#ffc850";
const ACCENT_GREEN = "#44ffaa";
const MUTED = "rgba(175,175,155,0.55)";
const TEXT = "#e0e0d0";

const BASE = `${import.meta.env.BASE_URL ?? "/"}data`;

// ── Types ──────────────────────────────────────────────────────────────────

type Meta = {
  cycle: string;
  version: string;
  build: string;
  extracted_at: string;
  counts: {
    strings_total: number;
    strings_index: number;
    catalogue_rows: number;
    deltas_added: number;
    deltas_changed: number;
    deltas_removed: number;
  };
};

type CatalogueRow = {
  typeID: number;
  label: string;
  text: string | null;
  desc: string | null;
  group: string;
};

type CatalogueDoc = Record<string, CatalogueRow[] | Array<{ typeID: number; text: string; desc: string | null }>>;

type CycleDeltas = {
  added: string[];
  changed: string[];
  removed: string[];
};

type EventType = { eventTypeName: string };

// ── Hooks ───────────────────────────────────────────────────────────────────

function useJson<T>(url: string, enabled: boolean): { data: T | null; loading: boolean; error: string | null } {
  const [data, setData] = useState<T | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!enabled || data) return;
    let cancelled = false;
    setLoading(true);
    setError(null);
    fetch(url)
      .then(r => { if (!r.ok) throw new Error(`HTTP ${r.status}`); return r.json(); })
      .then(j => { if (!cancelled) setData(j as T); })
      .catch(e => { if (!cancelled) setError(String(e.message ?? e)); })
      .finally(() => { if (!cancelled) setLoading(false); });
    return () => { cancelled = true; };
  }, [url, enabled, data]);

  return { data, loading, error };
}

// ── Subcomponents ──────────────────────────────────────────────────────────

function Header({ meta }: { meta: Meta | null }) {
  return (
    <div style={{
      display: "flex", alignItems: "center", gap: 12, marginBottom: 16, flexWrap: "wrap",
    }}>
      <span style={{ color: ACCENT, fontWeight: 700, fontSize: 16, letterSpacing: "0.06em" }}>
        ◇ GAME DATA VIEWPORT
      </span>
      {meta && (
        <span style={{
          fontSize: 10, color: MUTED, fontFamily: "monospace",
          background: "rgba(255,71,0,0.06)", border: "1px solid rgba(255,71,0,0.15)",
          padding: "2px 8px", letterSpacing: "0.1em",
        }}>
          {meta.cycle.toUpperCase()} · {meta.version} · build {meta.build}
        </span>
      )}
    </div>
  );
}

function TabStrip({ active, onChange }: { active: SubTab; onChange: (t: SubTab) => void }) {
  const TABS: Array<[SubTab, string]> = [
    ["catalogue", "▣ CATALOGUE"],
    ["strings",   "≣ STRINGS"],
    ["deltas",    "Δ CYCLE DELTAS"],
    ["events",    "✦ EVENT TYPES"],
    ["viewport3d", "◯ 3D PREVIEW"],
  ];
  return (
    <div style={{ display: "flex", borderBottom: "2px solid rgba(255,71,0,0.2)", marginBottom: 12, flexWrap: "wrap" }}>
      {TABS.map(([t, label]) => (
        <button key={t} onClick={() => onChange(t)} style={{
          fontFamily: "inherit", fontSize: 11, fontWeight: 700, letterSpacing: "0.1em",
          padding: "7px 14px", border: "none", cursor: "pointer",
          background: active === t ? "rgba(255,71,0,0.12)" : "transparent",
          color: active === t ? ACCENT : "rgba(255,255,255,0.35)",
          borderBottom: active === t ? `2px solid ${ACCENT}` : "2px solid transparent",
          marginBottom: -2,
        }}>{label}</button>
      ))}
    </div>
  );
}

type SubTab = "catalogue" | "strings" | "deltas" | "events" | "viewport3d";

// ── Catalogue subview ──────────────────────────────────────────────────────

const GROUP_META: Record<string, { label: string; accent: string; emoji: string }> = {
  structures:               { label: "Structures",        accent: ACCENT,       emoji: "▣" },
  turrets:                  { label: "Turrets",           accent: ACCENT_AMBER, emoji: "⊞" },
  shells_and_nursery:       { label: "Shell System",      accent: ACCENT_GREEN, emoji: "◉" },
  refuge:                   { label: "Refuge",            accent: ACCENT_BLUE,  emoji: "✦" },
  ecosystem_dungeons:       { label: "Ecosystem",         accent: ACCENT_GREEN, emoji: "≣" },
  sanctuary_new_structures: { label: "New This Cycle",    accent: ACCENT,       emoji: "★" },
  kitbash_strings:          { label: "Kitbash (preview)", accent: ACCENT_AMBER, emoji: "⚙" },
};

function CatalogueView() {
  const { data, loading, error } = useJson<CatalogueDoc>(`${BASE}/game-data-catalogue.json`, true);
  if (loading) return <Loading label="Loading catalogue…" />;
  if (error)   return <ErrorBox text={`Could not load catalogue: ${error}`} />;
  if (!data)   return null;

  const groups = Object.keys(data).filter(k => GROUP_META[k]);

  return (
    <div style={{ display: "grid", gap: 14 }}>
      {groups.map(key => {
        const rows = data[key] as Array<CatalogueRow | { typeID: number; text: string; desc: string | null }>;
        const meta = GROUP_META[key];
        return (
          <section key={key}>
            <div style={{
              display: "flex", alignItems: "baseline", gap: 8, marginBottom: 6,
            }}>
              <span style={{ color: meta.accent, fontWeight: 700, letterSpacing: "0.12em", fontSize: 12 }}>
                {meta.emoji} {meta.label.toUpperCase()}
              </span>
              <span style={{ fontSize: 10, color: MUTED }}>
                {rows.length} entries
              </span>
            </div>
            <div style={{
              display: "grid", gap: 4,
              gridTemplateColumns: "repeat(auto-fill, minmax(280px, 1fr))",
            }}>
              {rows.map((r, i) => (
                <CatalogueCard key={`${key}-${i}`} row={r} accent={meta.accent} />
              ))}
            </div>
          </section>
        );
      })}
    </div>
  );
}

function CatalogueCard({ row, accent }: {
  row: CatalogueRow | { typeID: number; text: string; desc: string | null };
  accent: string;
}) {
  const label = "label" in row ? row.label : row.text;
  const text = row.text;
  const desc = row.desc;
  return (
    <div style={{
      background: "rgba(255,255,255,0.02)",
      border: `1px solid ${accent}33`,
      borderLeft: `2px solid ${accent}`,
      borderRadius: 2,
      padding: "8px 10px",
      fontSize: 11,
    }}>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline", gap: 8 }}>
        <span style={{ color: TEXT, fontWeight: 700 }}>{label}</span>
        <span style={{ fontSize: 9, color: MUTED, fontFamily: "monospace" }}>#{row.typeID}</span>
      </div>
      {text && text !== label && (
        <div style={{ marginTop: 2, color: "rgba(220,220,200,0.7)", fontSize: 10 }}>{text}</div>
      )}
      {desc && (
        <div style={{ marginTop: 4, color: MUTED, fontSize: 10, lineHeight: 1.4 }}>{desc}</div>
      )}
    </div>
  );
}

// ── Strings subview ───────────────────────────────────────────────────────

function StringsView() {
  const { data, loading, error } = useJson<Record<string, string>>(`${BASE}/game-data-strings-index.json`, true);
  const [q, setQ] = useState("");
  const [limit, setLimit] = useState(100);

  const filtered = useMemo(() => {
    if (!data) return [] as Array<[string, string]>;
    const qLc = q.trim().toLowerCase();
    if (qLc.length === 0) return Object.entries(data).slice(0, limit);
    if (qLc.length < 2) return [];
    const out: Array<[string, string]> = [];
    for (const [tid, text] of Object.entries(data)) {
      // typeID exact match or substring match on text
      if (tid === qLc || text.toLowerCase().includes(qLc)) {
        out.push([tid, text]);
        if (out.length >= limit) break;
      }
    }
    return out;
  }, [data, q, limit]);

  if (loading) return <Loading label="Loading 216,785-entry strings index…" />;
  if (error)   return <ErrorBox text={`Could not load strings: ${error}`} />;

  return (
    <div>
      <div style={{ display: "flex", gap: 8, marginBottom: 12, alignItems: "center" }}>
        <input
          value={q}
          onChange={e => setQ(e.target.value)}
          placeholder="search game text or typeID…"
          style={{
            flex: 1, minWidth: 200,
            background: "rgba(255,255,255,0.04)",
            border: "1px solid rgba(255,255,255,0.12)",
            color: TEXT, fontSize: 12, padding: "6px 12px", outline: "none",
            borderRadius: 2,
          }}
        />
        <select
          value={limit}
          onChange={e => setLimit(Number(e.target.value))}
          style={{
            background: "rgba(255,255,255,0.04)",
            border: "1px solid rgba(255,255,255,0.12)",
            color: TEXT, fontSize: 11, padding: "5px 8px",
          }}
        >
          <option value={50}>50 results</option>
          <option value={100}>100 results</option>
          <option value={500}>500 results</option>
        </select>
      </div>
      <div style={{ fontSize: 10, color: MUTED, marginBottom: 8 }}>
        {data && (
          q.trim().length === 0
            ? <>Showing first {Math.min(limit, Object.keys(data).length)} of {Object.keys(data).length.toLocaleString()} display strings. Type to search.</>
            : <>{filtered.length} matches{filtered.length >= limit ? " (capped — narrow your query)" : ""}.</>
        )}
      </div>
      <div style={{ display: "grid", gap: 2 }}>
        {filtered.map(([tid, text]) => (
          <div key={tid} style={{
            display: "grid", gridTemplateColumns: "84px 1fr",
            gap: 8, padding: "4px 8px",
            fontSize: 11,
            background: "rgba(255,255,255,0.02)",
            borderLeft: "2px solid rgba(255,71,0,0.25)",
          }}>
            <span style={{ color: MUTED, fontFamily: "monospace", fontSize: 10 }}>#{tid}</span>
            <span style={{ color: TEXT }}>{text}</span>
          </div>
        ))}
        {q.trim().length === 1 && (
          <div style={{ color: MUTED, fontSize: 11, padding: 12 }}>Type at least 2 characters to search.</div>
        )}
      </div>
    </div>
  );
}

// ── Cycle deltas subview ──────────────────────────────────────────────────

function DeltasView() {
  const { data, loading, error } = useJson<CycleDeltas>(`${BASE}/game-data-cycle-deltas.json`, true);
  if (loading) return <Loading label="Loading cycle deltas…" />;
  if (error)   return <ErrorBox text={`Could not load deltas: ${error}`} />;
  if (!data)   return null;

  const sections: Array<[string, string[], string, string]> = [
    ["NEW IN SANCTUARY", data.added, ACCENT_GREEN, "+"],
    ["CONTENT ROTATED", data.changed, ACCENT_AMBER, "Δ"],
    ["REMOVED FROM CYCLE 5", data.removed, "#ff5070", "−"],
  ];

  return (
    <div style={{ display: "grid", gap: 14 }}>
      {sections.map(([label, items, accent, glyph]) => (
        <section key={label}>
          <div style={{ color: accent, fontWeight: 700, fontSize: 12, letterSpacing: "0.12em", marginBottom: 6 }}>
            {glyph}  {label}  ({items.length})
          </div>
          {items.length === 0 ? (
            <div style={{ color: MUTED, fontSize: 11 }}>—</div>
          ) : (
            <div style={{ display: "grid", gap: 2 }}>
              {items.map(p => (
                <div key={p} style={{
                  fontFamily: "monospace", fontSize: 11,
                  color: TEXT,
                  background: "rgba(255,255,255,0.02)",
                  borderLeft: `2px solid ${accent}`,
                  padding: "3px 8px",
                }}>{p}</div>
              ))}
            </div>
          )}
        </section>
      ))}
    </div>
  );
}

// ── Event types subview ──────────────────────────────────────────────────

function EventTypesView() {
  const { data, loading, error } = useJson<Record<string, EventType>>(`${BASE}/game-data-eventtypes.json`, true);
  if (loading) return <Loading label="Loading event types…" />;
  if (error)   return <ErrorBox text={`Could not load events: ${error}`} />;
  if (!data)   return null;
  const rows = Object.entries(data);
  return (
    <div style={{ display: "grid", gap: 2 }}>
      <div style={{ fontSize: 10, color: MUTED, marginBottom: 6 }}>
        {rows.length} canonical event types (carries forward from Cycle 5).
      </div>
      {rows.map(([id, e]) => (
        <div key={id} style={{
          display: "grid", gridTemplateColumns: "60px 1fr",
          fontSize: 11, padding: "3px 8px",
          background: "rgba(255,255,255,0.02)",
          borderLeft: `2px solid ${ACCENT}55`,
        }}>
          <span style={{ color: MUTED, fontFamily: "monospace" }}>#{id}</span>
          <span style={{ color: TEXT }}>{e.eventTypeName || "(unnamed)"}</span>
        </div>
      ))}
    </div>
  );
}

// ── 3D viewport (placeholder for now) ─────────────────────────────────────

// Hand-curated GLB stand-ins for each ship and structure class, shipped under
// /public/models/ and rendered with the same point-cloud + edge-wireframe styling
// as the Keeper viewport (see components/KeeperViewport.tsx). These are NOT
// decoded from the live .cmf/.black client assets — when CCP starts shipping .cmf
// and we wire up a real loader, we swap these for the extracted geometry.
const MODEL_ROSTER: Array<{ file: string; label: string; group: string; accent: number }> = [
  // Ships
  { file: "lai.glb",      label: "Lai",         group: "Frigates",   accent: 0xff4700 },
  { file: "haf.glb",      label: "Haf",         group: "Frigates",   accent: 0xff4700 },
  { file: "carom.glb",    label: "Carom",       group: "Frigates",   accent: 0xff4700 },
  { file: "reflex.glb",   label: "Reflex",      group: "Frigates",   accent: 0xff4700 },
  { file: "stride.glb",   label: "Stride",      group: "Frigates",   accent: 0xff4700 },
  { file: "lorha.glb",    label: "Lorha",       group: "Destroyers", accent: 0xff4700 },
  { file: "tades.glb",    label: "Tades",       group: "Destroyers", accent: 0xff4700 },
  { file: "maul.glb",     label: "Maul",        group: "Destroyers", accent: 0xff4700 },
  { file: "wend.glb",     label: "Wend",        group: "Haulers",    accent: 0x64b4ff },
  { file: "mcf.glb",      label: "MCF",         group: "Haulers",    accent: 0x64b4ff },
  { file: "usv.glb",      label: "USV",         group: "Shuttles",   accent: 0x64b4ff },
  { file: "chumaq.glb",   label: "Chumaq",      group: "Cruisers",   accent: 0xff4700 },
  { file: "recurve.glb",  label: "Recurve",     group: "Cruisers",   accent: 0xff4700 },
  { file: "reiver.glb",   label: "Reiver",      group: "Cruisers",   accent: 0xff4700 },
  // Structures
  { file: "gate.glb",      label: "Smart Gate",   group: "Structures", accent: 0xffc800 },
  { file: "turret.glb",    label: "Smart Turret", group: "Structures", accent: 0xffc800 },
  { file: "assembly.glb",  label: "Assembly",     group: "Structures", accent: 0xffc800 },
  { file: "printer.glb",   label: "Printer",      group: "Structures", accent: 0xffc800 },
  { file: "refinery.glb",  label: "Refinery",     group: "Structures", accent: 0xffc800 },
  { file: "shipyard.glb",  label: "Shipyard",     group: "Structures", accent: 0xffc800 },
  { file: "silo.glb",      label: "Silo",         group: "Structures", accent: 0xffc800 },
  { file: "hangar.glb",    label: "Hangar",       group: "Structures", accent: 0xffc800 },
  { file: "warehouse.glb", label: "Warehouse",    group: "Structures", accent: 0xffc800 },
  { file: "tether.glb",    label: "Tether",       group: "Structures", accent: 0xffc800 },
  { file: "wall.glb",      label: "Wall",         group: "Structures", accent: 0xffc800 },
  // World props
  { file: "asteroid.glb",  label: "Asteroid",     group: "World",      accent: 0x44ffaa },
  { file: "asteroid2.glb", label: "Asteroid II",  group: "World",      accent: 0x44ffaa },
];

function Viewport3D() {
  const mountRef = useRef<HTMLDivElement | null>(null);
  const [selected, setSelected] = useState<string>(MODEL_ROSTER[0].file);
  const [loadState, setLoadState] = useState<"loading" | "ready" | "error">("loading");

  const groups = useMemo(() => {
    const m = new Map<string, typeof MODEL_ROSTER>();
    for (const r of MODEL_ROSTER) {
      const arr = m.get(r.group) ?? [];
      arr.push(r);
      m.set(r.group, arr);
    }
    return Array.from(m.entries());
  }, []);

  const current = useMemo(
    () => MODEL_ROSTER.find(r => r.file === selected) ?? MODEL_ROSTER[0],
    [selected],
  );

  useEffect(() => {
    const mount = mountRef.current;
    if (!mount) return;

    setLoadState("loading");
    let cancelled = false;
    let raf = 0;
    const disposables: Array<THREE.BufferGeometry | THREE.Material | THREE.Texture> = [];

    const w = mount.clientWidth || 800;
    const h = 360;

    const renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true });
    renderer.setPixelRatio(window.devicePixelRatio);
    renderer.setSize(w, h);
    renderer.setClearColor(0x000000, 0);
    mount.appendChild(renderer.domElement);

    const scene = new THREE.Scene();
    const camera = new THREE.PerspectiveCamera(45, w / h, 0.05, 100);
    camera.position.set(0, 1.0, 4.2);
    camera.lookAt(0, 0, 0);

    scene.add(new THREE.AmbientLight(0xffffff, 0.15));

    // Grid floor in the model's accent colour
    const grid = new THREE.GridHelper(8, 16, current.accent, current.accent);
    const gridMat = grid.material as THREE.Material;
    gridMat.transparent = true;
    gridMat.opacity = 0.10;
    grid.position.y = -1.1;
    scene.add(grid);
    disposables.push(gridMat);

    const group = new THREE.Group();
    scene.add(group);

    const edgeMats: THREE.LineBasicMaterial[] = [];
    const ptMats: THREE.PointsMaterial[] = [];

    const loader = new GLTFLoader();
    const base = import.meta.env.BASE_URL || "/";
    loader.load(
      `${base}models/${current.file}`,
      (gltf) => {
        if (cancelled) return;
        const model = gltf.scene;
        // Auto-fit to viewport
        const box = new THREE.Box3().setFromObject(model);
        const size = box.getSize(new THREE.Vector3());
        const maxDim = Math.max(size.x, size.y, size.z) || 1;
        const scale = 2.0 / maxDim;
        model.scale.setScalar(scale);
        const center = box.getCenter(new THREE.Vector3()).multiplyScalar(scale);
        model.position.sub(center);

        // Per-mesh: hide the original mesh, add a sparse point cloud + edge wires
        model.traverse((child) => {
          if (!(child instanceof THREE.Mesh)) return;
          child.visible = false;
          const pos = child.geometry.attributes.position;
          if (!pos) return;

          const step = Math.max(1, Math.floor(pos.count / 8000));
          const pts: number[] = [];
          for (let i = 0; i < pos.count; i += step) {
            pts.push(pos.getX(i), pos.getY(i), pos.getZ(i));
          }
          if (pts.length > 0) {
            const pg = new THREE.BufferGeometry();
            pg.setAttribute("position", new THREE.Float32BufferAttribute(pts, 3));
            disposables.push(pg);
            const pm = new THREE.PointsMaterial({
              color: current.accent,
              size: 0.022,
              opacity: 0.45,
              transparent: true,
              sizeAttenuation: true,
              blending: THREE.AdditiveBlending,
              depthWrite: false,
            });
            disposables.push(pm);
            ptMats.push(pm);
            const points = new THREE.Points(pg, pm);
            points.position.copy(child.position);
            points.rotation.copy(child.rotation);
            points.scale.copy(child.scale);
            child.parent?.add(points);
          }

          const eg = new THREE.EdgesGeometry(child.geometry, 25);
          disposables.push(eg);
          const em = new THREE.LineBasicMaterial({
            color: current.accent,
            opacity: 0.22,
            transparent: true,
            blending: THREE.AdditiveBlending,
          });
          disposables.push(em);
          edgeMats.push(em);
          const edges = new THREE.LineSegments(eg, em);
          edges.position.copy(child.position);
          edges.rotation.copy(child.rotation);
          edges.scale.copy(child.scale);
          child.parent?.add(edges);
        });

        group.add(model);
        setLoadState("ready");
      },
      undefined,
      (err) => {
        console.warn(`[GameDataPanel] Failed to load ${current.file}:`, err);
        if (!cancelled) setLoadState("error");
      },
    );

    let t = 0;
    const animate = () => {
      t += 0.005;
      group.rotation.y += 0.004;
      group.rotation.x = Math.sin(t * 0.5) * 0.08;
      const edgePulse = 0.18 + Math.sin(t * 1.4) * 0.04;
      for (const m of edgeMats) m.opacity = edgePulse;
      const ptPulse = 0.40 + Math.sin(t * 1.4 + 0.5) * 0.08;
      for (const m of ptMats) m.opacity = ptPulse;
      renderer.render(scene, camera);
      raf = requestAnimationFrame(animate);
    };
    animate();

    const ro = new ResizeObserver(() => {
      const nw = mount.clientWidth || w;
      renderer.setSize(nw, h);
      camera.aspect = nw / h;
      camera.updateProjectionMatrix();
    });
    ro.observe(mount);

    return () => {
      cancelled = true;
      cancelAnimationFrame(raf);
      ro.disconnect();
      for (const d of disposables) (d as { dispose?: () => void }).dispose?.();
      renderer.dispose();
      if (renderer.domElement.parentElement === mount) {
        mount.removeChild(renderer.domElement);
      }
    };
  }, [current.file, current.accent]);

  const accentHex = `#${current.accent.toString(16).padStart(6, "0")}`;

  return (
    <div>
      {/* Viewer */}
      <div style={{
        background: "rgba(255,255,255,0.02)",
        border: `1px solid ${accentHex}33`,
        borderRadius: 2,
        padding: 12,
        marginBottom: 12,
        minHeight: 380,
        position: "relative",
      }}>
        <div ref={mountRef} style={{ width: "100%", height: 360, display: "grid", placeItems: "center" }} />
        {loadState === "loading" && (
          <div style={{
            position: "absolute", top: 18, left: 18,
            color: ACCENT_AMBER, fontSize: 11, fontFamily: "monospace",
          }}>○ Loading {current.label}…</div>
        )}
        {loadState === "error" && (
          <div style={{
            position: "absolute", top: 18, left: 18,
            color: "#ff5070", fontSize: 11, fontFamily: "monospace",
          }}>⚠ Model file missing: /models/{current.file}</div>
        )}
        {loadState === "ready" && (
          <div style={{
            position: "absolute", top: 14, right: 18,
            color: accentHex, fontSize: 10, fontFamily: "monospace",
            letterSpacing: "0.12em", textTransform: "uppercase",
          }}>◇ {current.label} · {current.group}</div>
        )}
      </div>

      {/* Picker, grouped by class */}
      <div style={{ display: "flex", flexWrap: "wrap", gap: 14, marginBottom: 14 }}>
        {groups.map(([groupName, entries]) => (
          <div key={groupName} style={{ minWidth: 160 }}>
            <div style={{
              fontSize: 9, color: MUTED, fontFamily: "monospace",
              letterSpacing: "0.18em", textTransform: "uppercase", marginBottom: 6,
            }}>── {groupName} ──</div>
            <div style={{ display: "flex", flexDirection: "column", gap: 3 }}>
              {entries.map(r => {
                const isActive = r.file === selected;
                const entryAccent = `#${r.accent.toString(16).padStart(6, "0")}`;
                return (
                  <button
                    key={r.file}
                    type="button"
                    onClick={() => setSelected(r.file)}
                    style={{
                      textAlign: "left",
                      background: isActive ? `${entryAccent}1f` : "transparent",
                      border: `1px solid ${isActive ? entryAccent : "rgba(255,255,255,0.06)"}`,
                      color: isActive ? entryAccent : TEXT,
                      padding: "4px 9px",
                      fontSize: 11,
                      fontFamily: "inherit",
                      cursor: "pointer",
                      letterSpacing: "0.04em",
                    }}
                  >
                    {isActive ? "◆" : "◇"} {r.label}
                  </button>
                );
              })}
            </div>
          </div>
        ))}
      </div>

      {/* Caption */}
      <div style={{ fontSize: 11, color: TEXT, lineHeight: 1.6 }}>
        <div style={{ color: ACCENT, fontWeight: 700, marginBottom: 6 }}>◇ 3D Model Browser</div>
        <p style={{ margin: "0 0 6px 0", color: "rgba(220,220,200,0.85)" }}>
          Hand-curated GLB stand-ins for each EVE Frontier ship and structure class, rendered with
          the same point-cloud + edge-wireframe styling as the Keeper viewport. Click any entry to
          load it.
        </p>
        <p style={{ margin: 0, color: MUTED, fontSize: 10 }}>
          Future iteration: when CCP starts shipping <code style={{ color: ACCENT_AMBER }}>.cmf</code>{" "}
          files in the client (currently the Sanctuary build ships{" "}
          <code style={{ color: ACCENT_AMBER }}>.gr2</code> / <code style={{ color: ACCENT_AMBER }}>.black</code>{" "}
          only), we'll wire up a real loader from{" "}
          <a href="https://github.com/carbonengine/mesh" target="_blank" rel="noreferrer"
             style={{ color: ACCENT_BLUE }}>carbonengine/mesh</a>{" "}
          and stream the live extracted geometry instead.
        </p>
      </div>
    </div>
  );
}

// ── Shared chrome ─────────────────────────────────────────────────────────

function Loading({ label }: { label: string }) {
  return <div style={{ color: ACCENT_AMBER, fontSize: 11, padding: 12 }}>● {label}</div>;
}

function ErrorBox({ text }: { text: string }) {
  return (
    <div style={{
      color: "#ff5070", fontSize: 11, padding: 12,
      background: "rgba(255,80,112,0.06)", border: "1px solid rgba(255,80,112,0.25)",
    }}>
      ⚠ {text}
    </div>
  );
}

// ── Top-level panel ───────────────────────────────────────────────────────

export function GameDataPanel() {
  const [tab, setTab] = useState<SubTab>("catalogue");
  const { data: meta } = useJson<Meta>(`${BASE}/game-data-meta.json`, true);

  return (
    <div style={{ padding: 20, maxWidth: 1000, margin: "0 auto" }}>
      <Header meta={meta} />
      <TabStrip active={tab} onChange={setTab} />
      {tab === "catalogue"  && <CatalogueView />}
      {tab === "strings"    && <StringsView />}
      {tab === "deltas"     && <DeltasView />}
      {tab === "events"     && <EventTypesView />}
      {tab === "viewport3d" && <Viewport3D />}

      {meta && (
        <div style={{
          marginTop: 18, paddingTop: 10,
          borderTop: "1px solid rgba(255,255,255,0.06)",
          fontSize: 9, color: MUTED, fontFamily: "monospace",
        }}>
          extracted {meta.extracted_at} · strings {meta.counts.strings_index.toLocaleString()} indexed of {meta.counts.strings_total.toLocaleString()} total · catalogue {meta.counts.catalogue_rows} rows · deltas +{meta.counts.deltas_added} Δ{meta.counts.deltas_changed} −{meta.counts.deltas_removed}
        </div>
      )}
    </div>
  );
}
