import {chromium} from '/home/rawdata/.npm-global/lib/node_modules/openclaw/node_modules/playwright-core/index.mjs';
import {writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const base=process.env.QA_BASE??'http://127.0.0.1:5213',live=base.startsWith('https:'),out=new URL('./',import.meta.url).pathname,PREF='cradleos:casino:slot-motion:v1',KEY='cradleos:casino:practice:v2';
const cases=live?[['fresh desktop',1440,'reduce',null,'Scrapyard Circuit','animated'],['fresh mobile',390,'no-preference',null,'Salvage Reels','animated']]:[['fresh desktop',1440,'reduce',null,'Scrapyard Circuit','animated'],['fresh mobile',390,'no-preference',null,'Scrapyard Circuit','animated'],['fresh classic',1440,'reduce',null,'Salvage Reels','animated'],['invalid',1440,'reduce','invalid','Scrapyard Circuit','animated'],['blocked preference',1440,'reduce','blocked','Scrapyard Circuit','animated'],['explicit system',1440,'reduce','system','Scrapyard Circuit','system'],['explicit instant',390,'no-preference','instant','Scrapyard Circuit','instant']];
const report={base,mode:'fresh isolated browser Play Money RNG spins, no wallet/chain actions',checks:[],errors:[]};const b=await chromium.launch({executablePath:'/home/rawdata/.cache/ms-playwright/chromium-1228/chrome-linux/chrome',args:['--no-sandbox','--no-proxy-server']});
try{for(const [name,width,reducedMotion,pref,game,expected] of cases){const c=await b.newContext({viewport:{width,height:1000},reducedMotion});const p=await c.newPage();p.on('pageerror',e=>report.errors.push(e.message));await p.addInitScript(([k,v])=>{if(v==='blocked'){const get=Storage.prototype.getItem;Storage.prototype.getItem=function(key){if(key===k)throw new DOMException('blocked');return get.call(this,key);};} },[PREF,pref]);await p.goto(base+'/#/casino');await p.locator('.lounge-game-tile').first().waitFor();if(pref&&pref!=='blocked'){await p.evaluate(([k,v])=>localStorage.setItem(k,v),[PREF,pref]);await p.reload();}await p.locator('.lounge-game-tile').filter({hasText:game}).click();const ctl=p.getByRole('combobox',{name:'Game animation'});assert.equal(await ctl.inputValue(),expected);await p.locator('.lounge-start').click();await p.waitForTimeout(170);const committed=await p.evaluate(k=>JSON.parse(sessionStorage.getItem(k)),KEY);let transforms=[];
if(expected==='animated'){assert.equal(await p.locator('.round-active').count(),1);const selector=game==='Salvage Reels'?'.casino-moving-reels .reel-moving > .game-icon':'.slot-reel-strip';const first=await p.locator(selector).evaluateAll(es=>es.map(e=>getComputedStyle(e).transform));assert(first.length>0&&first.some(x=>x!=='none'));await p.waitForTimeout(300);const second=await p.locator(selector).evaluateAll(es=>es.map(e=>getComputedStyle(e).transform));assert(second.some((x,i)=>x!==first[i]));transforms=[first,second];}
else assert.equal(await p.locator('.round-active,.slot-reel-window').count(),0);
await p.waitForFunction(()=>!document.querySelector('.round-active'));const end=await p.evaluate(k=>JSON.parse(sessionStorage.getItem(k)),KEY);assert.equal(end.sequence,1);assert.equal(end.balance,committed.balance);assert.deepEqual(end.history,committed.history);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));report.checks.push({name,width,reducedMotion,selected:expected,transforms});console.log(name+' PASS');if(name.startsWith('fresh'))await p.screenshot({path:out+`${live?'live':'preview'}-${name.replaceAll(' ','-')}.png`,fullPage:false});await c.close();}assert.deepEqual(report.errors,[]);}finally{await writeFile(out+(live?'slots-live-browser.json':'slots-browser.json'),JSON.stringify(report,null,2));await b.close();}
