import {chromium} from '/home/rawdata/.npm-global/lib/node_modules/openclaw/node_modules/playwright-core/index.mjs';
import {writeFile,readFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const base=process.env.QA_BASE??'http://127.0.0.1:5215',live=base.startsWith('https:'),out=new URL('./',import.meta.url).pathname,tag=live?'live':'preview',KEY='cradleos:casino:practice:v2',fixtures=JSON.parse(await readFile(out+'fixtures.json','utf8'));
const report={base,mode:'Isolated free Play Money RNG; viewport emulation, no wallet; actual temporal capture',checks:[],errors:[],assetFailures:[]};
const b=await chromium.launch({executablePath:'/home/rawdata/.cache/ms-playwright/chromium-1228/chrome-linux/chrome',args:['--no-sandbox','--no-proxy-server']});
const read=p=>p.evaluate(k=>JSON.parse(sessionStorage.getItem(k)),KEY),idle=p=>p.waitForFunction(()=>!document.querySelector('.round-active'));
const frame=p=>p.locator('.lai-jump-stage').evaluate(e=>({t:+e.dataset.progress,phase:e.dataset.phase,ship:e.querySelector('.lai-hull').getAttribute('transform'),opacity:e.querySelector('.lai-hull').getAttribute('opacity'),speed:e.querySelector('.lai-speed strong').textContent,worldX:+e.querySelector('.lai-hull').dataset.worldX,cameraX:+e.querySelector('.lai-hull').dataset.cameraX,shape:(()=>{const b=e.querySelector('.lai-hull>image').getBoundingClientRect();return{width:b.width,height:b.height}})(),thrust:+e.querySelector('.lai-exhaust').getAttribute('opacity'),debris:[...e.querySelectorAll('.lai-fragment')].map(x=>x.getAttribute('transform')),stars:[...e.querySelectorAll('.lai-starfield circle')].map(x=>x.getAttribute('cx'))}));
const init=async(width,motion='no-preference')=>{const c=await b.newContext({viewport:{width,height:950},reducedMotion:motion,recordVideo:width===390?{dir:out+tag+'-video',size:{width:390,height:950}}:undefined}),p=await c.newPage();p.on('pageerror',e=>report.errors.push(e.message));p.on('response',r=>{if(r.url().includes('/casino/lai-jump/')&&r.status()>=400)report.assetFailures.push(r.url())});await p.goto(base+'/#/casino');await p.locator('.lounge-game-tile').filter({hasText:'Jump Threshold'}).click();await p.locator('.lai-hull').waitFor();return {c,p};};
try{
for(const width of live?[390,1440]:[320,390,1440]){const {c,p}=await init(width,width===1440?'reduce':'no-preference');assert.equal(await p.getByRole('combobox',{name:'Game animation'}).inputValue(),'animated');const seen=new Set();
for(let attempt=0;attempt<8&&seen.size<2;attempt++){
await p.getByRole('spinbutton',{name:'Target multiplier'}).fill(!seen.has('warped')?'1.01':'1000');await p.locator('.lounge-start').click();const committed=await read(p),r=committed.history[0],phase=r.values[0]>=r.values[1]?'warped':'destroyed',frames=[];
for(const target of [.12,.4,.69,.732,.77,.84,.9,.98]){await p.waitForFunction(t=>Number(document.querySelector('.lai-jump-stage')?.getAttribute('data-progress'))>=t,target);const f=await frame(p);frames.push(f);await p.locator('.lai-jump-stage').screenshot({path:out+`${tag}-${width}-${phase}-${target}.png`});}
assert.equal(frames[0].phase,'accelerating');assert.notEqual(frames[0].ship,frames[1].ship);assert(frames[1].worldX>frames[0].worldX);for(const f of frames){assert(!/scale|rotate/.test(f.ship));assert(Math.abs(f.shape.width-frames[0].shape.width)<.1);assert(Math.abs(f.shape.height-frames[0].shape.height)<.1);assert.deepEqual(f.stars,frames[0].stars)}
if(phase==='destroyed'){const f=frames.find(f=>f.t>.72);assert.equal(f.debris.length,9);assert.equal(f.thrust,0);assert.notDeepEqual(f.debris,frames.at(-1).debris);assert.equal(await p.locator('.lai-warp-wake').count(),0)}else{assert.equal(await p.locator('.lai-warp-wake').count(),1);assert.equal(await p.locator('.lai-explosion').count(),0)}
await idle(p);const end=await frame(p);assert.equal(end.phase,phase);assert.equal(+end.opacity,0);assert.deepEqual(await read(p),committed);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));report.checks.push({width,phase,values:r.values,frames,end,ledgerUnchanged:true});console.log(width,phase,'PASS');seen.add(phase);
}assert.equal(seen.size,2);await c.close();}
if(!live)for(const boundary of ['reload-win','reload-loss','hidden','resize','instant','system']){const {c,p}=await init(390,boundary==='system'?'reduce':'no-preference');
if(boundary.startsWith('reload')){const saved=fixtures[boundary==='reload-win'?'win':'loss'];await p.evaluate(([k,s])=>sessionStorage.setItem(k,JSON.stringify(s)),[KEY,saved]);await p.reload();await p.locator('.lai-jump-stage').waitFor();assert.deepEqual(await read(p),saved);assert.equal(await p.locator('.lai-jump-stage').getAttribute('data-phase'),boundary==='reload-win'?'warped':'destroyed');assert.equal(await p.locator('.round-active').count(),0)}else{if(boundary==='instant'||boundary==='system')await p.getByRole('combobox',{name:'Game animation'}).selectOption(boundary);await p.locator('.lounge-start').click();const paid=await read(p);await p.waitForTimeout(200);if(boundary==='hidden')await p.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'))});if(boundary==='resize')await p.setViewportSize({width:320,height:950});if(boundary==='instant'||boundary==='system')assert.equal((await frame(p)).t,1);await idle(p);assert.deepEqual(await read(p),paid)}report.checks.push({boundary,ok:true});console.log(boundary,'PASS');await c.close()}
assert.deepEqual(report.errors,[]);assert.deepEqual(report.assetFailures,[]);
}catch(e){report.failure=String(e);throw e}finally{await writeFile(out+tag+'-browser.json',JSON.stringify(report,null,2));await b.close()}
