import {chromium} from '/home/rawdata/.npm-global/lib/node_modules/openclaw/node_modules/playwright-core/index.mjs';
import {writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const base=process.env.QA_BASE??'http://127.0.0.1:5216',tag=process.env.QA_TAG??'development',live=base.startsWith('https:'),out=new URL('./',import.meta.url).pathname,KEY='cradleos:casino:practice:v2';
const report={base,mode:'Actual app, isolated browser-local free Play Money; viewport emulation; no wallet',checks:[],errors:[],assetFailures:[]};
const b=await chromium.launch({executablePath:'/home/rawdata/.cache/ms-playwright/chromium-1228/chrome-linux/chrome',args:['--no-sandbox','--no-proxy-server']});
const read=p=>p.evaluate(k=>JSON.parse(sessionStorage.getItem(k)),KEY),idle=p=>p.waitForFunction(()=>!document.querySelector('.round-active'));
async function init(width,reduce=false){const c=await b.newContext({viewport:{width,height:950},reducedMotion:reduce?'reduce':'no-preference'}),p=await c.newPage();p.on('pageerror',e=>report.errors.push(e.message));p.on('response',r=>{if(r.status()>=400&&/\/assets\//.test(r.url()))report.assetFailures.push(r.url())});await p.goto(base+'/#/casino');await p.locator('.lounge-game-tile').filter({hasText:'Plinko'}).click();await p.locator('.lounge-plinko').waitFor();return{c,p};}
const observe=p=>p.evaluate(()=>{window.framesPlinko=[];const capture=()=>{const board=document.querySelector('.lounge-plinko svg');if(!board)return;const balls=[...board.querySelectorAll('.plinko-ball')].map(e=>({i:+e.dataset.ball,x:+e.getAttribute('cx'),y:+e.getAttribute('cy'),opacity:+e.closest('[data-flight]').getAttribute('opacity')}));window.framesPlinko.push({t:+board.dataset.elapsed,balls,hits:[...board.querySelectorAll('.plinko-impact')].map(e=>[+e.getAttribute('cx'),+e.getAttribute('cy')])});if(!board.dataset.landed||board.dataset.landed!=='true')requestAnimationFrame(capture)};requestAnimationFrame(capture)});
try{
for(const width of live?[390,1440]:[320,390,1440])for(const count of [1,10]){const {c,p}=await init(width,width===1440);assert.equal(await p.getByRole('combobox',{name:'Game animation'}).inputValue(),'animated');await p.locator('fieldset').getByRole('button',{name:String(count),exact:true}).click();await p.getByRole('button',{name:count===10?'High':'Low',exact:true}).click();await p.locator('.lounge-start').click();await observe(p);const paid=await read(p);assert.equal(paid.pack.rounds.length,count);await p.waitForTimeout(700);await p.locator('.lounge-plinko').screenshot({path:out+`${tag}-${width}-${count}-flight.png`});await idle(p);await p.locator('.lounge-plinko').screenshot({path:out+`${tag}-${width}-${count}-rest.png`});assert.deepEqual(await read(p),paid);const frames=await p.evaluate(()=>window.framesPlinko);assert(frames.length>30);const moving=frames.filter(f=>f.balls[0]?.y<217);assert(moving.length>20);assert(moving.some((f,i)=>i>0&&f.balls[0].y<moving[i-1].balls[0].y),'upward rebound');
for(const f of frames)for(let i=0;i<f.balls.length;i++)for(let j=i+1;j<f.balls.length;j++){const a=f.balls[i],z=f.balls[j];if(a.opacity>.01&&z.opacity>.01)assert(Math.hypot(a.x-z.x,a.y-z.y)>=5.99,'ball separation')}
assert(frames.some(f=>f.hits.length),'actual contact flashes');const end=frames.at(-1);for(const ball of end.balls){const values=paid.pack.rounds[ball.i].values;assert.equal(ball.x,42+18*values.reduce((a,b)=>a+b,0));assert.equal(ball.y,219);if(count>1)assert.equal(ball.opacity,0)}
assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));report.checks.push({width,count,profile:paid.pack.profile,values:paid.pack.rounds.map(r=>r.values),frames,ledgerUnchanged:true});console.log(width,count,'PASS');await c.close();}
if(!live)for(const boundary of ['instant','system','hidden','resize','reload','profile']){const {c,p}=await init(390,boundary==='system');await p.locator('fieldset').getByRole('button',{name:'10',exact:true}).click();if(['instant','system'].includes(boundary))await p.getByRole('combobox',{name:'Game animation'}).selectOption(boundary);await p.locator('.lounge-start').click();const paid=await read(p);await p.waitForTimeout(180);if(boundary==='hidden')await p.evaluate(()=>{Object.defineProperty(document,'hidden',{value:true,configurable:true});document.dispatchEvent(new Event('visibilitychange'))});if(boundary==='resize')await p.setViewportSize({width:320,height:950});if(boundary==='reload')await p.reload();if(['instant','system'].includes(boundary))assert.equal(await p.locator('.lounge-plinko svg').getAttribute('data-landed'),'true');await idle(p);assert.deepEqual(await read(p),paid);assert(await p.locator('[data-flight]').evaluateAll(es=>es.every(e=>+e.getAttribute('opacity')===0)));if(boundary==='profile'){await p.getByRole('button',{name:'High',exact:true}).click();assert.equal(await p.locator('.plinko-ball').count(),0);assert((await p.locator('.casino-board-caption').innerText()).includes('Next drop preview'));assert.deepEqual(await read(p),paid)}report.checks.push({boundary,ok:true});console.log(boundary,'PASS');await c.close();}
assert.deepEqual(report.errors,[]);assert.deepEqual(report.assetFailures,[]);
}catch(e){report.failure=String(e);throw e}finally{await b.close();await writeFile(out+tag+'-browser.json',JSON.stringify(report,null,2));}
