import {chromium} from '/home/rawdata/.npm-global/lib/node_modules/openclaw/node_modules/playwright-core/index.mjs';
import fs from 'node:fs/promises';import assert from 'node:assert/strict';
const OUT='research/cradleos-null-vault-motion-20261008',URL=process.env.QA_URL??'http://127.0.0.1:5199/',TAG=process.env.QA_TAG??'dev',KEY='cradleos:casino:practice:v2';
const fixture=JSON.parse(await fs.readFile('research/cradleos-casino-slot-identities-20261008/fixtures.json','utf8')).slot_vault,full=JSON.parse(await fs.readFile('research/cradleos-casino-slot-motion-20261008/feature-fixtures.json','utf8')).full;
const b=await chromium.launch({executablePath:'/home/rawdata/.cache/ms-playwright/chromium-1228/chrome-linux/chrome',args:['--no-sandbox','--no-proxy-server']});const report={checks:[],phases:[],errors:[]};
const save=p=>p.evaluate(k=>JSON.parse(sessionStorage.getItem(k)),KEY);
async function inject(p,r,cursor){const f={...structuredClone(r),cursor},round={id:1,game:r.key,stake:r.stake,payout:r.payout,values:[1,r.frames.length],label:'Saved feature'};const s={version:2,balance:1000000-r.stake+r.payout,sequence:1,history:[round],hand:null,table:null,pack:{game:r.key,rounds:[round],slot:f}};await p.evaluate(([k,s])=>sessionStorage.setItem(k,JSON.stringify(s)),[KEY,s]);await p.reload();await p.locator('.fleet-board').waitFor();await p.locator('.fleet-board').scrollIntoViewIfNeeded();return s;}
const start=p=>p.locator('.fleet-reveal-controls button').first().click();
const idle=p=>p.waitForFunction(()=>!document.querySelector('.round-active'));
async function phase(p,at,label){await p.waitForFunction(t=>performance.now()-Number(document.querySelector('.fleet-board').dataset.motionStart)>=t,at);const x=await p.locator('.fleet-board').evaluate(e=>({elapsed:performance.now()-+e.dataset.motionStart,cursor:+e.dataset.cursor,raw:e.dataset.rawStopped,aria:e.querySelector('.fleet-grid').getAttribute('aria-label'),instrument:e.querySelector('.vault-instrument').textContent,shutters:e.querySelectorAll('.vault-socket-shutter').length,visibleShutters:[...e.querySelectorAll('.vault-socket-shutter')].filter(x=>+getComputedStyle(x).opacity>.2).length,coins:e.querySelectorAll('.fleet-coin').length,masked:[...e.querySelectorAll('.fleet-cell')].filter(x=>x.title==='Unrevealed').map(x=>({coin:x.classList.contains('fleet-coin'),text:x.innerText,hidden:x.firstElementChild.getAttribute('aria-hidden')})),locks:[...e.querySelectorAll('.fleet-locked')].map(x=>({title:x.title,moving:x.getAnimations({subtree:true}).filter(a=>a.playState==='running').length})),scanner:[...e.querySelectorAll('.vault-socket-shutter>i')].map(x=>getComputedStyle(x).transform)}));report.phases.push({label,...x});return x;}
try{for(const width of JSON.parse(process.env.QA_WIDTHS??'[320,390,1440]')){
 const ctx=await b.newContext({viewport:{width,height:1000},hasTouch:width<1000,reducedMotion:'no-preference'}),p=await ctx.newPage();p.on('pageerror',e=>report.errors.push(e.message));await p.goto(URL+'#/casino-station');await p.locator('.lounge-game-tile').first().waitFor();assert.equal(await p.locator('.casino-station').count(),0);assert.equal(await p.getByRole('button',{name:'Station ↗',exact:true}).count(),0);report.checks.push(`${width}: retired station redirects to web casino`);
 for(const cursor of [0,1,2]){const before=await inject(p,fixture,cursor);if(cursor===0)assert.equal(await p.locator('.fleet-coin').count(),0,'saved board cannot expose coin backgrounds');await start(p);const first=await phase(p,200,`${width}-${cursor}-scan`);const known=cursor?fixture.frames[cursor-1].coins.filter(Boolean).length:0;assert.equal(first.coins,known);assert.equal(first.masked.length,15-known);assert(first.masked.every(c=>!c.coin&&!c.text.includes('×')&&c.hidden==='true'));assert(first.locks.every(c=>c.moving===0));if(cursor)assert(first.instrument.includes('VAULT BREACHED'));const scan=await phase(p,650,`${width}-${cursor}-scan-moving`);assert(scan.scanner.some((x,i)=>x!==first.scanner[i]));assert.equal(scan.coins,known);const opening=await phase(p,1750,`${width}-${cursor}-opening`);assert(opening.visibleShutters>0&&opening.visibleShutters<first.visibleShutters);assert.equal(opening.cursor,cursor);assert(opening.locks.every(c=>c.moving===0));if(width===390&&cursor===1)await p.locator('.fleet-board').screenshot({path:`${OUT}/${TAG}-opening.png`});const reading=await phase(p,3070,`${width}-${cursor}-read`);assert.equal(reading.visibleShutters,0);assert.equal(reading.cursor,cursor);assert.equal(reading.raw,'true');assert.equal(reading.coins,fixture.frames[cursor].coins.filter(Boolean).length);await idle(p);const after=await save(p);assert.equal(after.balance,before.balance);assert.equal(after.sequence,before.sequence);assert.equal(after.pack.slot.cursor,cursor+1);assert.deepEqual(await p.locator('.fleet-cell').evaluateAll(es=>es.map(e=>+e.dataset.symbol)),fixture.frames[cursor].grid.flat());assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));report.checks.push(`${width}: frame${cursor} scan/stops/read pause, exact result and one cursor`);}
 const before=await inject(p,full,1);await start(p);const c=await phase(p,300,`${width}-collect`);assert.equal(c.shutters,0);assert.equal(c.locks.length,15);await idle(p);assert.equal((await save(p)).balance,before.balance);assert.equal((await save(p)).pack.slot.cursor,2);report.checks.push(`${width}: full grid collection only`);await ctx.close();}
 const ctx=await b.newContext({viewport:{width:390,height:1000},reducedMotion:'no-preference'}),p=await ctx.newPage();p.on('pageerror',e=>report.errors.push(e.message));await p.goto(URL+'#/casino');await p.locator('.lounge-game-tile').first().waitFor();
 for(const mode of ['reduce-back','hidden','resize','reload','rapid','skip']){await p.emulateMedia({reducedMotion:'no-preference'});await p.setViewportSize({width:390,height:1000});const before=await inject(p,fixture,1);if(mode==='skip'){await p.getByRole('button',{name:'Reveal all',exact:true}).click();assert.equal((await save(p)).pack.slot.cursor,fixture.frames.length);}else{if(mode==='rapid')await p.locator('.fleet-reveal-controls button').first().evaluate(e=>{e.click();e.click();e.click();});else await start(p);await p.waitForTimeout(250);if(mode==='reduce-back'){await p.emulateMedia({reducedMotion:'reduce'});await p.waitForTimeout(80);await p.emulateMedia({reducedMotion:'no-preference'});}if(mode==='hidden')await p.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));});if(mode==='resize')await p.setViewportSize({width:350,height:1000});if(['reduce-back','hidden','resize'].includes(mode)){await p.waitForTimeout(100);assert.equal(await p.locator('.vault-socket-shutter').count(),0);}if(mode==='reload'){await p.reload();await p.locator('.fleet-board').waitFor();assert.equal((await save(p)).pack.slot.cursor,1);await start(p);}await idle(p);assert.equal((await save(p)).pack.slot.cursor,2);}assert.equal((await save(p)).balance,before.balance);assert.equal((await save(p)).sequence,before.sequence);report.checks.push(`${mode}: one reveal, unchanged ledger`);}
 // A fresh RNG spin uses the same visible scan, not merely a saved-receipt path.
 if(await p.getByRole('button',{name:'Reveal all',exact:true}).count())await p.getByRole('button',{name:'Reveal all',exact:true}).click();const before=await save(p);await p.locator('.lounge-start').click();const fresh=await phase(p,650,'fresh-scan');assert.equal(fresh.masked.length,15);await idle(p);const after=await save(p);assert.equal(after.sequence,before.sequence+1);assert.equal(after.balance,before.balance-after.pack.slot.stake+after.pack.slot.payout);report.checks.push('fresh RNG spin visibly scans and charges once');await ctx.close();assert.deepEqual(report.errors,[]);await fs.writeFile(`${OUT}/${TAG}-qa.json`,JSON.stringify(report,null,2));console.log(JSON.stringify({checks:report.checks,errors:report.errors},null,2));}catch(e){await fs.writeFile(`${OUT}/${TAG}-failure.json`,JSON.stringify(report,null,2));throw e;}finally{await b.close();}
