// Additional attributes beyond CPU/PG — extracted from wiki_attributes screenshots 2026-03-14
export const MODULE_ATTRIBUTES: Record<string, {
  name: string;
  group?: string;
  category?: string;
  // All attributes found — use snake_case keys matching the in-game label
  [key: string]: string | number | undefined;
}> = {
  "heat_exchanger_xs": {
    name: "Heat Exchanger XS",
    group: "Heat Ejector",
    charge_size: "Small",
    reload_time_s: 10.0,
    mass_kg: 120000,
    activation_cost_gj: 20.0,
    max_modules_of_this_group_allowed: 1,
    conductance_multiplier_x: 1.6,
    volume_m3: 40,
    capacity_m3: 5,
    charges_per_cycle: 1,
    activation_time_duration_s: 10.0,
    used_with_charge_group: "Heat Sink Charge",
    can_be_fitted_to: "Shuttle, Corvette"
  },
  "heat_exchanger_s": {
    name: "Heat Exchanger S",
    group: "Heat Ejector",
    charge_size: "Small",
    reload_time_s: 10.0,
    mass_kg: 240000,
    activation_cost_gj: 30.0,
    conductance_multiplier_x: 1.4,
    volume_m3: 80,
    capacity_m3: 10,
    charges_per_cycle: 2,
    activation_time_duration_s: 10.0,
    used_with_charge_group: "Heat Sink Charge",
    can_be_fitted_to: "Frigate, Destroyer"
  },
  "cryogenic_ejector_s": {
    name: "Cryogenic Ejector S",
    group: "Heat Ejector",
    reload_time_s: 55.0,
    mass_kg: 240000,
    activation_cost_gj: 30.0,
    max_modules_of_this_group_allowed: 1,
    temperature_bonus_t: -30,
    volume_m3: 80,
    capacity_m3: 10,
    charges_per_cycle: 10,
    activation_time_duration_s: 5.0,
    used_with_charge_group: "Heat Sink Charge",
    can_be_fitted_to: "Frigate, Destroyer"
  },
  "systematic_armor_restorer_iv": {
    name: "Systematic Armor Restorer IV",
    group: "Armor Repair Unit",
    volume_m3: 200,
    mass_kg: 251280,
    activation_cost_gj: 30.0,
    activation_time_duration_s: 8.0,
    armor_hitpoints_repaired_hp: 700
  },
  "systematic_armor_restorer_iii": {
    name: "Systematic Armor Restorer III",
    group: "Armor Repair Unit",
    volume_m3: 150,
    mass_kg: 750000,
    activation_cost_gj: 20.0,
    activation_time_duration_s: 7.0,
    armor_hitpoints_repaired_hp: 550
  },
  "systematic_armor_restorer_ii": {
    name: "Systematic Armor Restorer II",
    group: "Armor Repair Unit",
    volume_m3: 150,
    mass_kg: 750000,
    activation_cost_gj: 15.0,
    activation_time_duration_s: 6.5,
    armor_hitpoints_repaired_hp: 300
  },
  "thermalnetic_nanitic_brace_iv": {
    name: "Thermalnetic Nanitic Brace IV",
    group: "Nanitic Brace",
    volume_m3: 280,
    mass_kg: 560000,
    active_kinetic_damage_resistance_pct: -20,
    active_thermal_damage_resistance_pct: -20,
    capacitor_recharge_penalty_gj_s: 0.4,
    armor_hitpoint_bonus_pct: 0
  },
  "thermalnetic_nanitic_brace_iii": {
    name: "Thermalnetic Nanitic Brace III",
    group: "Nanitic Brace",
    volume_m3: 140,
    mass_kg: 280000,
    active_kinetic_damage_resistance_pct: -17.5,
    active_thermal_damage_resistance_pct: -17.5,
    capacitor_recharge_penalty_gj_s: 0.3,
    armor_hitpoint_bonus_pct: 0
  },
  "thermalnetic_nanitic_brace_ii": {
    name: "Thermalnetic Nanitic Brace II",
    group: "Nanitic Brace",
    volume_m3: 70,
    mass_kg: 140000,
    active_kinetic_damage_resistance_pct: -15,
    active_thermal_damage_resistance_pct: -15,
    capacitor_recharge_penalty_gj_s: 0.3,
    armor_hitpoint_bonus_pct: 0
  },
  "thermal_electro_nanitic_brace_iv": {
    name: "Thermal-electro Nanitic Brace IV",
    group: "Nanitic Brace",
    volume_m3: 280,
    mass_kg: 560000,
    active_em_damage_resistance_pct: -20,
    active_thermal_damage_resistance_pct: -20,
    capacitor_recharge_penalty_gj_s: 0.5,
    armor_hitpoint_bonus_pct: 0
  },
  "thermal_electro_nanitic_brace_iii": {
    name: "Thermal-electro Nanitic Brace III",
    group: "Nanitic Brace",
    volume_m3: 140,
    mass_kg: 280000,
    active_em_damage_resistance_pct: -17.5,
    active_thermal_damage_resistance_pct: -17.5,
    capacitor_recharge_penalty_gj_s: 0.4,
    armor_hitpoint_bonus_pct: 0
  },
  "thermal_electro_nanitic_brace_ii": {
    name: "Thermal-electro Nanitic Brace II",
    group: "Nanitic Brace",
    volume_m3: 70,
    mass_kg: 140000,
    active_em_damage_resistance_pct: -15,
    active_thermal_damage_resistance_pct: -15,
    capacitor_recharge_penalty_gj_s: 0.3,
    armor_hitpoint_bonus_pct: 0
  },
  "explonetic_electro_nanitic_brace_iv": {
    name: "Explonetic-electro Nanitic Brace IV",
    group: "Nanitic Brace",
    volume_m3: 80,
    mass_kg: 320000,
    active_em_damage_resistance_pct: -15,
    active_explosive_damage_resistance_pct: -15,
    active_kinetic_damage_resistance_pct: -15,
    capacitor_recharge_penalty_gj_s: 0.5,
    armor_hitpoint_bonus_pct: 0
  },
  "explonetic_electro_nanitic_brace_iii": {
    name: "Explonetic-electro Nanitic Brace III",
    group: "Nanitic Brace",
    volume_m3: 40,
    mass_kg: 160000,
    active_em_damage_resistance_pct: -12.5,
    active_explosive_damage_resistance_pct: -12.5,
    active_kinetic_damage_resistance_pct: -12.5,
    capacitor_recharge_penalty_gj_s: 0.4,
    armor_hitpoint_bonus_pct: 0
  },
  "explonetic_electro_nanitic_brace_ii": {
    name: "Explonetic-electro Nanitic Brace II",
    group: "Nanitic Brace",
    volume_m3: 20,
    mass_kg: 80000,
    active_em_damage_resistance_pct: -10,
    active_explosive_damage_resistance_pct: -10,
    active_kinetic_damage_resistance_pct: -10,
    capacitor_recharge_penalty_gj_s: 0.3,
    armor_hitpoint_bonus_pct: 0
  },
  "explo_electro_nanitic_brace_iv": {
    name: "Explo-electro Nanitic Brace IV",
    group: "Nanitic Brace",
    volume_m3: 80,
    mass_kg: 240000,
    active_em_damage_resistance_pct: -20,
    active_explosive_damage_resistance_pct: -20,
    capacitor_recharge_penalty_gj_s: 0.5,
    armor_hitpoint_bonus_pct: 0
  },
  "explo_electro_nanitic_brace_iii": {
    name: "Explo-electro Nanitic Brace III",
    group: "Nanitic Brace",
    volume_m3: 40,
    mass_kg: 120000,
    active_em_damage_resistance_pct: -17.5,
    active_explosive_damage_resistance_pct: -17.5,
    capacitor_recharge_penalty_gj_s: 0.4,
    armor_hitpoint_bonus_pct: 0
  },
  "explo_electro_nanitic_brace_ii": {
    name: "Explo-electro Nanitic Brace II",
    group: "Nanitic Brace",
    volume_m3: 20,
    mass_kg: 60000,
    active_em_damage_resistance_pct: -15,
    active_explosive_damage_resistance_pct: -15,
    capacitor_recharge_penalty_gj_s: 0.3,
    armor_hitpoint_bonus_pct: 0
  },
  "reactive_armor_plates_iv": {
    name: "Reactive Armor Plates IV",
    category: "Defensive System",
    mass_kg: 173180,
    activation_cost_gj: 15.0,
    armor_hitpoint_bonus_hp: 1700,
    max_modules_of_this_group_allowed: 2,
    reactivation_delay_s: 30.0,
    volume_m3: 170,
    active_em_damage_resistance_pct: -25,
    active_explosive_damage_resistance_pct: -25,
    active_kinetic_damage_resistance_pct: -25,
    active_thermal_damage_resistance_pct: -25,
    activation_time_duration_s: 12.0,
    cannot_auto_repeat: "True",
    passive_em_damage_resistance_bonus_pct: -50
  },
  "reactive_armor_plates_iii": {
    name: "Reactive Armor Plates III",
    category: "Defensive System",
    mass_kg: 200000,
    activation_cost_gj: 15.0,
    armor_hitpoint_bonus_hp: 1200,
    max_modules_of_this_group_allowed: 2,
    reactivation_delay_s: 30.0,
    volume_m3: 80,
    active_em_damage_resistance_pct: -25,
    active_explosive_damage_resistance_pct: -25,
    active_kinetic_damage_resistance_pct: -25,
    active_thermal_damage_resistance_pct: -25,
    activation_time_duration_s: 12.0,
    cannot_auto_repeat: "True",
    passive_em_damage_resistance_bonus_pct: -50
  },
  "reactive_armor_plates_ii": {
    name: "Reactive Armor Plates II",
    category: "Defensive System",
    mass_kg: 100000,
    activation_cost_gj: 15.0,
    armor_hitpoint_bonus_hp: 640,
    max_modules_of_this_group_allowed: 2,
    reactivation_delay_s: 30.0,
    volume_m3: 40,
    active_em_damage_resistance_pct: -25,
    active_explosive_damage_resistance_pct: -25,
    active_kinetic_damage_resistance_pct: -25,
    active_thermal_damage_resistance_pct: -25,
    activation_time_duration_s: 12.0,
    passive_em_damage_resistance_bonus_pct: -50,
    cannot_auto_repeat: "True"
  },
  "nimble_armor_plates_iv": {
    name: "Nimble Armor Plates IV",
    category: "Defensive System",
    volume_m3: 170,
    mass_kg: 173180,
    armor_hitpoint_bonus_hp: 1400,
    max_modules_of_this_group_allowed: 2,
    passive_em_damage_resistance_bonus_pct: -50
  },
  "nimble_armor_plates_iii": {
    name: "Nimble Armor Plates III",
    category: "Defensive System",
    volume_m3: 80,
    mass_kg: 200000,
    armor_hitpoint_bonus_hp: 1050,
    max_modules_of_this_group_allowed: 2,
    passive_em_damage_resistance_bonus_pct: -50
  },
  "nimble_armor_plates_ii": {
    name: "Nimble Armor Plates II",
    category: "Defensive System",
    volume_m3: 40,
    mass_kg: 100000,
    armor_hitpoint_bonus_hp: 580,
    max_modules_of_this_group_allowed: 2,
    passive_em_damage_resistance_bonus_pct: -50
  },
  "coated_armor_plates_iv": {
    name: "Coated Armor Plates IV",
    category: "Defensive System",
    mass_kg: 173180,
    armor_hitpoint_bonus_hp: 1900,
    max_modules_of_this_group_allowed: 2,
    volume_m3: 170,
    active_em_damage_resistance_pct: -15,
    active_explosive_damage_resistance_pct: -15,
    active_kinetic_damage_resistance_pct: -15,
    active_thermal_damage_resistance_pct: -15,
    capacitor_recharge_penalty_gj_s: 1.4,
    passive_em_damage_resistance_bonus_pct: -50
  },
  "coated_armor_plates_iii": {
    name: "Coated Armor Plates III",
    category: "Defensive System",
    mass_kg: 160000,
    armor_hitpoint_bonus_hp: 1320,
    max_modules_of_this_group_allowed: 2,
    volume_m3: 80,
    active_em_damage_resistance_pct: -12.5,
    active_explosive_damage_resistance_pct: -12.5,
    active_kinetic_damage_resistance_pct: -12.5,
    active_thermal_damage_resistance_pct: -12.5,
    capacitor_recharge_penalty_gj_s: 0.8,
    passive_em_damage_resistance_bonus_pct: -50
  },
  "coated_armor_plates_ii": {
    name: "Coated Armor Plates II",
    category: "Defensive System",
    mass_kg: 80000,
    armor_hitpoint_bonus_hp: 675,
    max_modules_of_this_group_allowed: 2,
    volume_m3: 40,
    active_em_damage_resistance_pct: -10,
    active_explosive_damage_resistance_pct: -10,
    active_kinetic_damage_resistance_pct: -10,
    active_thermal_damage_resistance_pct: -10,
    capacitor_recharge_penalty_gj_s: 0.4,
    passive_em_damage_resistance_bonus_pct: -50
  },
  "bulky_armor_plates_v": {
    name: "Bulky Armor Plates V",
    category: "Defensive System",
    volume_m3: 320,
    mass_kg: 346370,
    armor_hitpoint_bonus_hp: 3000,
    max_modules_of_this_group_allowed: 2,
    passive_em_damage_resistance_bonus_pct: -50
  },
  "bulky_armor_plates_iii": {
    name: "Bulky Armor Plates III",
    category: "Defensive System",
    volume_m3: 80,
    mass_kg: 448000,
    armor_hitpoint_bonus_hp: 1500,
    max_modules_of_this_group_allowed: 2,
    passive_em_damage_resistance_bonus_pct: -50
  },
  "bulky_armor_plates_ii": {
    name: "Bulky Armor Plates II",
    category: "Defensive System",
    volume_m3: 40,
    mass_kg: 224000,
    armor_hitpoint_bonus_hp: 750,
    max_modules_of_this_group_allowed: 2,
    passive_em_damage_resistance_bonus_pct: -50
  },
  "adaptive_nanitic_armor_weave_iv": {
    name: "Adaptive Nanitic Armor Weave IV",
    category: "Flex Armor Hardener",
    charge_size: "Small",
    reload_time_s: 0.0,
    mass_kg: 11430,
    activation_cost_gj: 0.5,
    max_modules_of_this_group_allowed: 1,
    volume_m3: 20,
    capacity_m3: 20,
    activation_time_duration_s: 60.0,
    used_with_charge_group: "Nanitic Armor Weave Sequencer",
    passive_em_damage_resistance_bonus_pct: -22,
    passive_explosive_damage_resistance_bonus_pct: -16,
    passive_kinetic_damage_resistance_bonus_pct: -16,
    passive_thermal_damage_resistance_bonus_pct: -16
  },
  "adaptive_nanitic_armor_weave_iii": {
    name: "Adaptive Nanitic Armor Weave III",
    category: "Flex Armor Hardener",
    charge_size: "Small",
    reload_time_s: 0.0,
    mass_kg: 140000,
    activation_cost_gj: 0.5,
    max_modules_of_this_group_allowed: 1,
    volume_m3: 40,
    capacity_m3: 20,
    activation_time_duration_s: 60.0,
    used_with_charge_group: "Nanitic Armor Weave Sequencer",
    passive_em_damage_resistance_bonus_pct: -20,
    passive_explosive_damage_resistance_bonus_pct: -16,
    passive_kinetic_damage_resistance_bonus_pct: -16,
    passive_thermal_damage_resistance_bonus_pct: -16
  },
  "adaptive_nanitic_armor_weave_ii": {
    name: "Adaptive Nanitic Armor Weave II",
    category: "Flex Armor Hardener",
    charge_size: "Small",
    reload_time_s: 0.0,
    mass_kg: 70000,
    activation_cost_gj: 0.5,
    max_modules_of_this_group_allowed: 1,
    volume_m3: 20,
    capacity_m3: 20,
    activation_time_duration_s: 60.0,
    used_with_charge_group: "Nanitic Armor Weave Sequencer",
    passive_em_damage_resistance_bonus_pct: -18,
    passive_explosive_damage_resistance_bonus_pct: -16,
    passive_kinetic_damage_resistance_bonus_pct: -16,
    passive_thermal_damage_resistance_bonus_pct: -16
  },
  "warp_entangler_vi": {
    name: "Warp Entangler VI",
    category: "Warp Scrambler",
    volume_m3: 50,
    mass_kg: 250000,
    activation_cost_gj: 10.0,
    activation_time_duration_s: 12.0,
    warp_scramble_strength: 1,
    optimal_range_km: 54.0,
    cannot_auto_repeat: "True",
    reactivation_delay_s: 45.0
  },
  "warp_entangler_v": {
    name: "Warp Entangler V",
    category: "Warp Scrambler",
    volume_m3: 50,
    mass_kg: 225000,
    activation_cost_gj: 10.0,
    activation_time_duration_s: 12.0,
    warp_scramble_strength: 1,
    optimal_range_km: 38.0,
    cannot_auto_repeat: "True",
    reactivation_delay_s: 45.0
  },
  "warp_entangler_iv": {
    name: "Warp Entangler IV",
    category: "Warp Scrambler",
    volume_m3: 50,
    mass_kg: 200000,
    activation_cost_gj: 10.0,
    activation_time_duration_s: 12.0,
    warp_scramble_strength: 1,
    optimal_range_km: 24.0,
    cannot_auto_repeat: "True",
    reactivation_delay_s: 45.0
  },
  "warp_entangler_iii": {
    name: "Warp Entangler III",
    category: "Warp Scrambler",
    volume_m3: 50,
    mass_kg: 175000,
    activation_cost_gj: 10.0,
    activation_time_duration_s: 12.0,
    warp_scramble_strength: 1,
    optimal_range_km: 20.0,
    cannot_auto_repeat: "True",
    reactivation_delay_s: 45.0
  },
  "warp_entangler_ii": {
    name: "Warp Entangler II",
    category: "Warp Scrambler",
    volume_m3: 50,
    mass_kg: 150000,
    activation_cost_gj: 10.0,
    activation_time_duration_s: 12.0,
    warp_scramble_strength: 1,
    optimal_range_km: 16.0,
    cannot_auto_repeat: "True",
    reactivation_delay_s: 45.0
  },
  "stasis_net_vi": {
    name: "Stasis Net VI",
    category: "Stasis Web",
    mass_kg: 250000,
    activation_cost_gj: 10.0,
    maximum_velocity_bonus_pct: -90,
    reactivation_delay_s: 30.0,
    volume_m3: 50,
    optimal_range_km: 24.0,
    activation_time_duration_s: 20.0,
    cannot_auto_repeat: "True"
  },
  "stasis_net_v": {
    name: "Stasis Net V",
    category: "Stasis Web",
    mass_kg: 225000,
    activation_cost_gj: 10.0,
    maximum_velocity_bonus_pct: -80,
    reactivation_delay_s: 30.0,
    volume_m3: 50,
    optimal_range_km: 24.0,
    activation_time_duration_s: 20.0,
    cannot_auto_repeat: "True"
  },
  "stasis_net_iv": {
    name: "Stasis Net IV",
    category: "Stasis Web",
    mass_kg: 200000,
    activation_cost_gj: 10.0,
    maximum_velocity_bonus_pct: -70,
    reactivation_delay_s: 30.0,
    volume_m3: 50,
    optimal_range_km: 24.0,
    activation_time_duration_s: 20.0,
    cannot_auto_repeat: "True"
  },
  "stasis_net_iii": {
    name: "Stasis Net III",
    category: "Stasis Web",
    mass_kg: 175000,
    activation_cost_gj: 10.0,
    maximum_velocity_bonus_pct: -65,
    reactivation_delay_s: 30.0,
    volume_m3: 50,
    optimal_range_km: 24.0,
    activation_time_duration_s: 20.0,
    cannot_auto_repeat: "True"
  },
  "stasis_net_ii": {
    name: "Stasis Net II",
    category: "Stasis Web",
    mass_kg: 150000,
    activation_cost_gj: 10.0,
    maximum_velocity_bonus_pct: -55,
    reactivation_delay_s: 30.0,
    volume_m3: 50,
    optimal_range_km: 24.0,
    activation_time_duration_s: 20.0,
    cannot_auto_repeat: "True"
  },
  "cargo_grid_vi": {
    name: "Cargo Grid VI",
    category: "Expanded Cargohold",
    volume_m3: 8320,
    cargo_capacity_bonus_m3: 7490,
    mass_kg: 4576000
  },
  "cargo_grid_v": {
    name: "Cargo Grid V",
    category: "Expanded Cargohold",
    volume_m3: 4160,
    cargo_capacity_bonus_m3: 3740,
    mass_kg: 2288000
  },
  "cargo_grid_iv": {
    name: "Cargo Grid IV",
    category: "Expanded Cargohold",
    volume_m3: 2080,
    cargo_capacity_bonus_m3: 1870,
    mass_kg: 1144000
  },
  "cargo_grid_iii": {
    name: "Cargo Grid III",
    category: "Expanded Cargohold",
    volume_m3: 1040,
    cargo_capacity_bonus_m3: 940,
    mass_kg: 572000
  },
  "cargo_grid_ii": {
    name: "Cargo Grid II",
    category: "Expanded Cargohold",
    volume_m3: 520,
    cargo_capacity_bonus_m3: 470,
    mass_kg: 286000
  },
  "reinforced_shield_generator_iv": {
    name: "Reinforced Shield Generator IV",
    category: "Defensive System",
    volume_m3: 940,
    mass_kg: 1002770,
    capacity_m3: 1,
    shield_recharge_rate_bonus_pct: 10,
    shield_hitpoint_bonus_hp: 1825,
    max_modules_of_this_group_allowed: 2,
    capacitor_recharge_penalty_gj_s: 0.6,
    signature_radius_modifier_m: 15.0
  },
  "reinforced_shield_generator_iii": {
    name: "Reinforced Shield Generator III",
    category: "Defensive System",
    volume_m3: 300,
    mass_kg: 600000,
    capacity_m3: 1,
    shield_recharge_rate_bonus_pct: 10,
    shield_hitpoint_bonus_hp: 950,
    max_modules_of_this_group_allowed: 2,
    capacitor_recharge_penalty_gj_s: 0.6,
    signature_radius_modifier_m: 10.0
  },
  "reinforced_shield_generator_ii": {
    name: "Reinforced Shield Generator II",
    category: "Defensive System",
    volume_m3: 120,
    mass_kg: 180000,
    capacity_m3: 1,
    shield_recharge_rate_bonus_pct: 10,
    shield_hitpoint_bonus_hp: 385,
    max_modules_of_this_group_allowed: 2,
    capacitor_recharge_penalty_gj_s: 0.6,
    signature_radius_modifier_m: 8.0
  },
  "bulwark_shield_generator_iv": {
    name: "Bulwark Shield Generator IV",
    category: "Defensive System",
    volume_m3: 624,
    mass_kg: 1002770,
    capacity_m3: 1,
    shield_hitpoint_bonus_hp: 2600,
    max_modules_of_this_group_allowed: 2,
    signature_radius_modifier_m: 15.0
  },
  "bulwark_shield_generator_iii": {
    name: "Bulwark Shield Generator III",
    category: "Defensive System",
    volume_m3: 300,
    mass_kg: 600000,
    capacity_m3: 1,
    shield_hitpoint_bonus_hp: 1400,
    max_modules_of_this_group_allowed: 2,
    signature_radius_modifier_m: 10.0
  },
  "bulwark_shield_generator_ii": {
    name: "Bulwark Shield Generator II",
    category: "Defensive System",
    volume_m3: 120,
    mass_kg: 180000,
    capacity_m3: 1,
    shield_hitpoint_bonus_hp: 500,
    max_modules_of_this_group_allowed: 2,
    signature_radius_modifier_m: 8.0
  },
  "attuned_shield_generator_iv": {
    name: "Attuned Shield Generator IV",
    category: "Defensive System",
    mass_kg: 1002770,
    activation_cost_gj: 20.0,
    max_modules_of_this_group_allowed: 2,
    reactivation_delay_s: 30.0,
    volume_m3: 300,
    capacity_m3: 1,
    signature_radius_m: 10.0,
    active_em_damage_resistance_pct: -25,
    active_explosive_damage_resistance_pct: -25,
    active_kinetic_damage_resistance_pct: -25,
    active_thermal_damage_resistance_pct: -25,
    shield_hitpoint_bonus_hp: 2210,
    activation_time_duration_s: 20.0,
    signature_radius_modifier_m: 15.0,
    cannot_auto_repeat: "True"
  },
  "attuned_shield_generator_iii": {
    name: "Attuned Shield Generator III",
    category: "Defensive System",
    mass_kg: 600000,
    activation_cost_gj: 15.0,
    max_modules_of_this_group_allowed: 2,
    reactivation_delay_s: 30.0,
    volume_m3: 300,
    capacity_m3: 1,
    signature_radius_m: 10.0,
    active_em_damage_resistance_pct: -25,
    active_explosive_damage_resistance_pct: -25,
    active_kinetic_damage_resistance_pct: -25,
    active_thermal_damage_resistance_pct: -25,
    shield_hitpoint_bonus_hp: 1190,
    activation_time_duration_s: 20.0,
    signature_radius_modifier_m: 10.0,
    cannot_auto_repeat: "True"
  },
  "attuned_shield_generator_ii": {
    name: "Attuned Shield Generator II",
    category: "Defensive System",
    mass_kg: 180000,
    activation_cost_gj: 10.0,
    max_modules_of_this_group_allowed: 2,
    reactivation_delay_s: 30.0,
    volume_m3: 120,
    capacity_m3: 1,
    signature_radius_m: 10.0,
    active_em_damage_resistance_pct: -25,
    active_explosive_damage_resistance_pct: -25,
    active_kinetic_damage_resistance_pct: -25,
    active_thermal_damage_resistance_pct: -25,
    shield_hitpoint_bonus_hp: 425,
    activation_time_duration_s: 20.0,
    signature_radius_modifier_m: 8.0,
    cannot_auto_repeat: "True"
  },
  "shield_restorer_iv": {
    name: "Shield Restorer IV",
    category: "Shield Recharger",
    volume_m3: 200,
    mass_kg: 251280,
    capacity_m3: 1,
    activation_cost_gj: 10.0,
    shield_recharge_rate_bonus_pct: 75,
    activation_time_duration_s: 10.0,
    cannot_auto_repeat: "True",
    reactivation_delay_s: 12.0
  },
  "shield_restorer_iii": {
    name: "Shield Restorer III",
    category: "Shield Recharger",
    volume_m3: 150,
    mass_kg: 525000,
    capacity_m3: 1,
    activation_cost_gj: 8.0,
    shield_recharge_rate_bonus_pct: 70,
    activation_time_duration_s: 10.0,
    cannot_auto_repeat: "True",
    reactivation_delay_s: 12.0
  },
  "shield_restorer_ii": {
    name: "Shield Restorer II",
    category: "Shield Recharger",
    volume_m3: 150,
    mass_kg: 450000,
    capacity_m3: 1,
    activation_cost_gj: 6.0,
    shield_recharge_rate_bonus_pct: 60,
    activation_time_duration_s: 10.0,
    cannot_auto_repeat: "True",
    reactivation_delay_s: 12.0
  },
  "thermal_field_array_iv": {
    name: "Thermal Field Array IV",
    category: "Shield Hardener",
    volume_m3: 3.5,
    mass_kg: 8750,
    active_thermal_damage_resistance_pct: -35,
    capacitor_recharge_penalty_gj_s: 0.5
  },
  "thermal_field_array_iii": {
    name: "Thermal Field Array III",
    category: "Shield Hardener",
    volume_m3: 3,
    mass_kg: 7500,
    active_thermal_damage_resistance_pct: -30,
    capacitor_recharge_penalty_gj_s: 0.4
  },
  "thermal_field_array_ii": {
    name: "Thermal Field Array II",
    category: "Shield Hardener",
    volume_m3: 2.5,
    mass_kg: 6250,
    active_thermal_damage_resistance_pct: -25,
    capacitor_recharge_penalty_gj_s: 0.3
  },
  "kinetic_field_array_iv": {
    name: "Kinetic Field Array IV",
    category: "Shield Hardener",
    volume_m3: 80,
    mass_kg: 400000,
    active_kinetic_damage_resistance_pct: -35,
    capacitor_recharge_penalty_gj_s: 0.5
  },
  "kinetic_field_array_iii": {
    name: "Kinetic Field Array III",
    category: "Shield Hardener",
    volume_m3: 40,
    mass_kg: 200000,
    active_kinetic_damage_resistance_pct: -30,
    capacitor_recharge_penalty_gj_s: 0.4
  },
  "kinetic_field_array_ii": {
    name: "Kinetic Field Array II",
    category: "Shield Hardener",
    volume_m3: 20,
    mass_kg: 100000,
    active_kinetic_damage_resistance_pct: -25,
    capacitor_recharge_penalty_gj_s: 0.3
  },
  "explosive_field_array_iv": {
    name: "Explosive Field Array IV",
    category: "Shield Hardener",
    volume_m3: 80,
    mass_kg: 400000,
    active_explosive_damage_resistance_pct: -35,
    capacitor_recharge_penalty_gj_s: 0.5
  },
  "explosive_field_array_iii": {
    name: "Explosive Field Array III",
    category: "Shield Hardener",
    volume_m3: 40,
    mass_kg: 200000,
    active_explosive_damage_resistance_pct: -30,
    capacitor_recharge_penalty_gj_s: 0.4
  },
  "explosive_field_array_ii": {
    name: "Explosive Field Array II",
    category: "Shield Hardener",
    volume_m3: 20,
    mass_kg: 100000,
    active_explosive_damage_resistance_pct: -25,
    capacitor_recharge_penalty_gj_s: 0.3
  },
  "em_field_array_iv": {
    name: "EM Field Array IV",
    category: "Shield Hardener",
    volume_m3: 80,
    mass_kg: 240000,
    active_em_damage_resistance_pct: -35,
    capacitor_recharge_penalty_gj_s: 0.5
  },
  "em_field_array_iii": {
    name: "EM Field Array III",
    category: "Shield Hardener",
    volume_m3: 40,
    mass_kg: 120000,
    active_em_damage_resistance_pct: -30,
    capacitor_recharge_penalty_gj_s: 0.4
  },
  "em_field_array_ii": {
    name: "EM Field Array II",
    category: "Shield Hardener",
    volume_m3: 20,
    mass_kg: 60000,
    active_em_damage_resistance_pct: -25,
    capacitor_recharge_penalty_gj_s: 0.3
  },
  "skip": {
    name: "Skip",
    category: "Warp Accelerator",
    mass_kg: 60000,
    activation_cost_gj: 5.0,
    max_modules_of_this_group_allowed: 1,
    maximum_velocity_bonus_pct: 420,
    reactivation_delay_s: 40.0,
    volume_m3: 20,
    cpu_load_tf: 20.0,
    thrust_n: 43000000,
    activation_time_duration_s: 6.0,
    turn_rate_bonus_pct: -100,
    capacitor_recharge_penalty_gj_s: 0.5,
    can_be_fitted_to: "Shuttle"
  },
  "lunge": {
    name: "Lunge",
    category: "Warp Accelerator",
    mass_kg: 60000,
    activation_cost_gj: 14.0,
    max_modules_of_this_group_allowed: 1,
    maximum_velocity_bonus_pct: 630,
    reactivation_delay_s: 40.0,
    volume_m3: 20,
    cpu_load_tf: 20.0,
    thrust_n: 1846230000,
    activation_time_duration_s: 10.0,
    turn_rate_bonus_pct: -100,
    capacitor_recharge_penalty_gj_s: 4.4,
    can_be_fitted_to: "Cruiser, Combat Battlecruiser"
  },
  "leap": {
    name: "Leap",
    category: "Warp Accelerator",
    mass_kg: 60000,
    activation_cost_gj: 12.0,
    max_modules_of_this_group_allowed: 1,
    maximum_velocity_bonus_pct: 630,
    reactivation_delay_s: 40.0,
    volume_m3: 20,
    cpu_load_tf: 20.0,
    thrust_n: 118143000,
    activation_time_duration_s: 12.0,
    turn_rate_bonus_pct: -100,
    capacitor_recharge_penalty_gj_s: 2.1,
    can_be_fitted_to: "Frigate, Destroyer"
  },
  "hop": {
    name: "Hop",
    category: "Warp Accelerator",
    mass_kg: 60000,
    activation_cost_gj: 8.0,
    max_modules_of_this_group_allowed: 1,
    maximum_velocity_bonus_pct: 350,
    reactivation_delay_s: 40.0,
    volume_m3: 20,
    cpu_load_tf: 20.0,
    thrust_n: 61920000,
    activation_time_duration_s: 9.0,
    turn_rate_bonus_pct: -100,
    capacitor_recharge_penalty_gj_s: 1.2,
    can_be_fitted_to: "Corvette, Frigate"
  },
  "afterburner_iv": {
    name: "Afterburner IV",
    category: "Propulsion Module",
    volume_m3: 20,
    mass_kg: 23073,
    max_modules_of_this_group_allowed: 1,
    maximum_velocity_bonus_pct: 350,
    capacitor_recharge_penalty_gj_s: 2.5,
    thrust_n: 288750000,
    can_be_fitted_to: "Cruiser, Combat Battlecruiser"
  },
  "afterburner_iii": {
    name: "Afterburner III",
    category: "Propulsion Module",
    volume_m3: 40,
    mass_kg: 120000,
    max_modules_of_this_group_allowed: 1,
    maximum_velocity_bonus_pct: 350,
    capacitor_recharge_penalty_gj_s: 1.8,
    thrust_n: 57000000,
    can_be_fitted_to: "Destroyer, Cruiser"
  },
  "afterburner_ii": {
    name: "Afterburner II",
    category: "Propulsion Module",
    volume_m3: 20,
    mass_kg: 60000,
    max_modules_of_this_group_allowed: 1,
    maximum_velocity_bonus_pct: 350,
    thrust_n: 23125000,
    capacitor_recharge_penalty_gj_s: 1,
    can_be_fitted_to: "Corvette, Frigate, Destroyer"
  },
  "rugged_shell": {
    name: "Rugged Shell",
    category: "Synthetic",
    volume_m3: 2,
    mass_kg: 80,
    repair_unit_capacitor_need_pct: -10
  },
  "reaping_shell": {
    name: "Reaping Shell",
    category: "Synthetic",
    volume_m3: 2,
    mass_kg: 80,
    cutting_laser_capacitor_need_pct: -10
  },
  "blank_shell": {
    name: "Blank Shell",
    category: "Synthetic",
    volume_m3: 2,
    mass_kg: 80
  },
  "ancient_shell": {
    name: "Ancient Shell",
    category: "Synthetic",
    volume_m3: 2,
    mass_kg: 80,
    capacitor_need_pct: -5,
    cpu: 15
  },
  "aggressive_shell": {
    name: "Aggressive Shell",
    category: "Synthetic",
    volume_m3: 2,
    mass_kg: 80,
    shield_restorer_capacitor_need_pct: -10
  },
  "hull_repairer": {
    name: "Hull Repairer",
    group: "Hull Repairer",
    volume_m3: 12.5,
    mass_kg: 1000,
    activation_cost_gj: 15.0,
    activation_time_duration_s: 8.0,
    structure_hitpoints_repaired_hp: 250
  },
  "tier_3_howitzer_m": {
    name: "Tier 3 Howitzer (M)",
    category: "Projectile Weapon",
    charge_size: "Medium",
    reload_time_s: 10.0,
    mass_kg: 58950,
    activation_cost_gj: 0.6,
    structure_hitpoints_hp: 250,
    accuracy_falloff_km: 37.5,
    turret_tracking: 0.33,
    volume_m3: 80,
    capacity_m3: 9.75,
    tech_level: "Level 1",
    rate_of_fire_s: 8.6,
    optimal_range_km: 28.85,
    charges_per_cycle: 1,
    damage_modifier_x: 1.2,
    used_with_charge_group: "Projectile Ammo",
    meta_level: "Level 0"
  },
  "tier_3_autocannon_s": {
    name: "Tier 3 Autocannon (S)",
    category: "Projectile Weapon",
    charge_size: "Small",
    reload_time_s: 6.0,
    mass_kg: 80000,
    activation_cost_gj: 0.3,
    structure_hitpoints_hp: 165,
    accuracy_falloff_km: 39.57,
    turret_tracking: 0.495,
    volume_m3: 20,
    capacity_m3: 24,
    tech_level: "Level 1",
    rate_of_fire_s: 1.6,
    optimal_range_km: 30.44,
    charges_per_cycle: 1,
    damage_modifier_x: 1.2,
    used_with_charge_group: "Gyrojet Ammunition",
    meta_level: "Level 0"
  },
  "tier_2_howitzer_m": {
    name: "Tier 2 Howitzer (M)",
    category: "Projectile Weapon",
    charge_size: "Medium",
    reload_time_s: 10.0,
    mass_kg: 57850,
    activation_cost_gj: 0.6,
    structure_hitpoints_hp: 250,
    accuracy_falloff_km: 35.87,
    turret_tracking: 0.32,
    volume_m3: 80,
    capacity_m3: 9.75,
    tech_level: "Level 1",
    rate_of_fire_s: 8.8,
    optimal_range_km: 27.59,
    charges_per_cycle: 1,
    damage_modifier_x: 1.1,
    used_with_charge_group: "Projectile Ammo",
    meta_level: "Level 0"
  },
  "tier_2_autocannon_s": {
    name: "Tier 2 Autocannon (S)",
    category: "Projectile Weapon",
    charge_size: "Small",
    reload_time_s: 6.0,
    mass_kg: 70000,
    activation_cost_gj: 0.3,
    structure_hitpoints_hp: 165,
    accuracy_falloff_km: 36.03,
    turret_tracking: 0.49,
    volume_m3: 20,
    capacity_m3: 24,
    tech_level: "Level 1",
    rate_of_fire_s: 1.8,
    optimal_range_km: 27.72,
    charges_per_cycle: 1,
    damage_modifier_x: 1.1,
    used_with_charge_group: "Gyrojet Ammunition",
    meta_level: "Level 0"
  },
  "base_howitzer_m": {
    name: "Base Howitzer (M)",
    category: "Projectile Weapon",
    charge_size: "Medium",
    reload_time_s: 10.0,
    mass_kg: 56750,
    activation_cost_gj: 0.6,
    structure_hitpoints_hp: 250,
    accuracy_falloff_km: 34.24,
    turret_tracking: 0.31,
    volume_m3: 80,
    capacity_m3: 9.75,
    tech_level: "Level 1",
    rate_of_fire_s: 9.0,
    optimal_range_km: 26.34,
    charges_per_cycle: 1,
    damage_modifier_x: 1,
    used_with_charge_group: "Projectile Ammo",
    meta_level: "Level 0"
  },
  "base_autocannon_s": {
    name: "Base Autocannon (S)",
    category: "Projectile Weapon",
    charge_size: "Small",
    reload_time_s: 6.0,
    mass_kg: 60000,
    activation_cost_gj: 0.3,
    structure_hitpoints_hp: 165,
    accuracy_falloff_km: 32.33,
    turret_tracking: 0.485,
    volume_m3: 20,
    capacity_m3: 24,
    tech_level: "Level 1",
    rate_of_fire_s: 2.0,
    optimal_range_km: 27.18,
    charges_per_cycle: 1,
    damage_modifier_x: 1,
    used_with_charge_group: "Gyrojet Ammunition",
    meta_level: "Level 0"
  },
  "tier_3_rapid_plasma_s": {
    name: "Tier 3 Rapid Plasma (S)",
    category: "Plasma Weapon",
    charge_size: "Small",
    reload_time_s: 7.0,
    mass_kg: 80000,
    activation_cost_gj: 0.6,
    structure_hitpoints_hp: 40,
    accuracy_falloff_km: 29.68,
    turret_tracking: 0.488,
    volume_m3: 20,
    capacity_m3: 18,
    tech_level: "Level 1",
    rate_of_fire_s: 2.5,
    optimal_range_km: 22.83,
    charges_per_cycle: 1,
    damage_modifier_x: 1.2,
    used_with_charge_group: "Plasma Charge",
    meta_level: "Level 0"
  },
  "tier_3_rapid_plasma_m": {
    name: "Tier 3 Rapid Plasma (M)",
    category: "Plasma Weapon",
    charge_size: "Medium",
    reload_time_s: 5.0,
    mass_kg: 68920,
    activation_cost_gj: 1.06,
    structure_hitpoints_hp: 40,
    accuracy_falloff_km: 13.37,
    turret_tracking: 0.37,
    volume_m3: 80,
    capacity_m3: 39,
    tech_level: "Level 1",
    rate_of_fire_s: 3.4,
    optimal_range_km: 10.28,
    charges_per_cycle: 1,
    damage_modifier_x: 1.2,
    used_with_charge_group: "Plasma Charge",
    meta_level: "Level 0"
  },
  "tier_2_rapid_plasma_s": {
    name: "Tier 2 Rapid Plasma (S)",
    category: "Plasma Weapon",
    charge_size: "Small",
    reload_time_s: 7.0,
    mass_kg: 70000,
    activation_cost_gj: 0.6,
    structure_hitpoints_hp: 40,
    accuracy_falloff_km: 28.26,
    turret_tracking: 0.484,
    volume_m3: 20,
    capacity_m3: 18,
    tech_level: "Level 1",
    rate_of_fire_s: 2.7,
    optimal_range_km: 21.74,
    charges_per_cycle: 1,
    damage_modifier_x: 1.1,
    used_with_charge_group: "Plasma Charge",
    meta_level: "Level 0"
  },
  "tier_2_rapid_plasma_m": {
    name: "Tier 2 Rapid Plasma (M)",
    category: "Plasma Weapon",
    charge_size: "Medium",
    reload_time_s: 9.0,
    mass_kg: 67820,
    activation_cost_gj: 1.06,
    structure_hitpoints_hp: 40,
    accuracy_falloff_km: 12.88,
    turret_tracking: 0.36,
    volume_m3: 80,
    capacity_m3: 39,
    tech_level: "Level 1",
    rate_of_fire_s: 3.6,
    optimal_range_km: 9.91,
    charges_per_cycle: 1,
    damage_modifier_x: 1.1,
    used_with_charge_group: "Plasma Charge",
    meta_level: "Level 0"
  },
  "rapid_plasma_m": {
    name: "Rapid Plasma (M)",
    category: "Plasma Weapon",
    charge_size: "Medium",
    reload_time_s: 9.0,
    mass_kg: 66720,
    activation_cost_gj: 1.06,
    structure_hitpoints_hp: 40,
    accuracy_falloff_km: 12.56,
    turret_tracking: 0.35,
    volume_m3: 80,
    capacity_m3: 39,
    tech_level: "Level 1",
    rate_of_fire_s: 3.8,
    optimal_range_km: 9.66,
    charges_per_cycle: 1,
    damage_modifier_x: 1,
    used_with_charge_group: "Plasma Charge",
    meta_level: "Level 0"
  },
  "base_rapid_plasma_s": {
    name: "Base Rapid Plasma (S)",
    category: "Plasma Weapon",
    charge_size: "Small",
    reload_time_s: 7.0,
    mass_kg: 60000,
    activation_cost_gj: 0.6,
    structure_hitpoints_hp: 40,
    accuracy_falloff_km: 26.14,
    turret_tracking: 0.48,
    volume_m3: 20,
    capacity_m3: 18,
    tech_level: "Level 1",
    rate_of_fire_s: 2.5,
    optimal_range_km: 20.11,
    charges_per_cycle: 1,
    damage_modifier_x: 1,
    used_with_charge_group: "Plasma Charge",
    meta_level: "Level 0"
  },
  "small_cutting_laser": {
    name: "Small Cutting Laser",
    category: "Asteroid Mining Laser",
    charge_size: "Small",
    reload_time_s: 1.0,
    mass_kg: 60000,
    activation_cost_gj: 4.0,
    turret_tracking: 1,
    volume_m3: 20,
    capacity_m3: 2,
    mining_efficiency_pct: 60,
    rate_of_fire_s: 4.0,
    optimal_range_km: 15.0,
    damage_modifier_x: 1,
    activation_time_duration_s: 4.0,
    residue_volume_multiplier_x: 0,
    residue_probability_pct: 0,
    used_with_charge_group: "Asteroid Mining Crystal",
    minimum_yield_m3: 16
  },
  "purified_moon_cutting_laser": {
    name: "Purified Moon Cutting Laser",
    category: "Asteroid Mining Laser",
    charge_size: "Large",
    reload_time_s: 1.0,
    mass_kg: 240000,
    activation_cost_gj: 44.0,
    turret_tracking: 0.5,
    volume_m3: 80,
    capacity_m3: 5,
    mining_efficiency_pct: 90,
    rate_of_fire_s: 3.0,
    optimal_range_km: 30.0,
    damage_modifier_x: 1,
    activation_time_duration_s: 6.0,
    residue_volume_multiplier_x: 0,
    residue_probability_pct: 0,
    used_with_charge_group: "Asteroid Mining Crystal",
    minimum_yield_m3: 186
  },
  "medium_cutting_laser": {
    name: "Medium Cutting Laser",
    category: "Asteroid Mining Laser",
    charge_size: "Medium",
    reload_time_s: 1.0,
    mass_kg: 41840,
    activation_cost_gj: 11.0,
    turret_tracking: 0.5,
    volume_m3: 75,
    capacity_m3: 3,
    mining_efficiency_pct: 70,
    rate_of_fire_s: 4.0,
    optimal_range_km: 20.0,
    damage_modifier_x: 1,
    activation_time_duration_s: 4.0,
    residue_volume_multiplier_x: 0,
    residue_probability_pct: 0,
    used_with_charge_group: "Asteroid Mining Crystal",
    minimum_yield_m3: 60
  },
  "crude_extractor": {
    name: "Crude Extractor",
    category: "Crude Extractor",
    charge_size: "Small",
    reload_time_s: 1.0,
    mass_kg: 100000,
    activation_cost_gj: 15.0,
    volume_m3: 20,
    capacity_m3: 10,
    mining_efficiency_pct: 90,
    optimal_range_km: 15.0,
    activation_time_duration_s: 60.0,
    residue_volume_multiplier_x: 0,
    residue_probability_pct: 0,
    used_with_charge_group: "Crude Mining Lens",
    minimum_yield_m3: 49
  },
  "tier_3_coilgun_s": {
    name: "Tier 3 Coilgun (S)",
    category: "Mass Driver Weapon",
    charge_size: "Small",
    reload_time_s: 9.0,
    mass_kg: 80000,
    activation_cost_gj: 0.8,
    structure_hitpoints_hp: 180,
    accuracy_falloff_km: 130.0,
    turret_tracking: 0.36,
    volume_m3: 20,
    capacity_m3: 12,
    rate_of_fire_s: 5.0,
    optimal_range_km: 100.0,
    charges_per_cycle: 1,
    damage_modifier_x: 1.2,
    used_with_charge_group: "Coilgun Charge"
  },
  "tier_3_coilgun_m": {
    name: "Tier 3 Coilgun (M)",
    category: "Mass Driver Weapon",
    charge_size: "Medium",
    reload_time_s: 6.0,
    mass_kg: 70190,
    activation_cost_gj: 1.4,
    structure_hitpoints_hp: 180,
    accuracy_falloff_km: 45.33,
    turret_tracking: 0.36,
    volume_m3: 80,
    capacity_m3: 26,
    rate_of_fire_s: 8.0,
    optimal_range_km: 34.87,
    charges_per_cycle: 1,
    damage_modifier_x: 1.2,
    used_with_charge_group: "Coilgun Charge"
  },
  "tier_2_coilgun_s": {
    name: "Tier 2 Coilgun (S)",
    category: "Mass Driver Weapon",
    charge_size: "Small",
    reload_time_s: 9.0,
    mass_kg: 70000,
    activation_cost_gj: 0.8,
    structure_hitpoints_hp: 180,
    accuracy_falloff_km: 121.88,
    turret_tracking: 0.355,
    volume_m3: 20,
    capacity_m3: 12,
    rate_of_fire_s: 5.0,
    optimal_range_km: 93.75,
    charges_per_cycle: 1,
    damage_modifier_x: 1.1,
    used_with_charge_group: "Coilgun Charge"
  },
  "tier_2_coilgun_m": {
    name: "Tier 2 Coilgun (M)",
    category: "Mass Driver Weapon",
    charge_size: "Medium",
    reload_time_s: 12.0,
    mass_kg: 69080,
    activation_cost_gj: 1.4,
    structure_hitpoints_hp: 180,
    accuracy_falloff_km: 43.04,
    turret_tracking: 0.355,
    volume_m3: 80,
    capacity_m3: 26,
    rate_of_fire_s: 8.0,
    optimal_range_km: 33.11,
    charges_per_cycle: 1,
    damage_modifier_x: 1.1,
    used_with_charge_group: "Coilgun Charge"
  },
  "base_coilgun_s": {
    name: "Base Coilgun (S)",
    category: "Mass Driver Weapon",
    charge_size: "Small",
    reload_time_s: 9.0,
    mass_kg: 60000,
    activation_cost_gj: 0.8,
    structure_hitpoints_hp: 180,
    accuracy_falloff_km: 113.04,
    turret_tracking: 0.35,
    volume_m3: 20,
    capacity_m3: 12,
    rate_of_fire_s: 9.0,
    optimal_range_km: 86.96,
    charges_per_cycle: 1,
    damage_modifier_x: 1,
    used_with_charge_group: "Coilgun Charge"
  },
  "base_coilgun_m": {
    name: "Base Coilgun (M)",
    category: "Mass Driver Weapon",
    charge_size: "Medium",
    reload_time_s: 12.0,
    mass_kg: 67980,
    activation_cost_gj: 1.4,
    structure_hitpoints_hp: 180,
    accuracy_falloff_km: 41.41,
    turret_tracking: 0.35,
    volume_m3: 80,
    capacity_m3: 26,
    rate_of_fire_s: 8.0,
    optimal_range_km: 31.86,
    charges_per_cycle: 1,
    damage_modifier_x: 1,
    used_with_charge_group: "Coilgun Charge"
  },
  "xoru_s": {
    name: "Xoru S",
    category: "Energy Lance",
    charge_size: "Medium",
    reload_time_s: 0.0,
    mass_kg: 51390,
    activation_cost_gj: 1.8,
    structure_hitpoints_hp: 40,
    turret_tracking: 600,
    volume_m3: 80,
    capacity_m3: 2.4,
    tech_level: "Level 1",
    damage_multiplier_bonus_per_cycle_pct: 20,
    maximum_damage_multiplier_bonus_pct: 340,
    rate_of_fire_s: 4.5,
    optimal_range_km: 39.81,
    charges_per_cycle: 1,
    damage_modifier_x: 1.2,
    used_with_charge_group: "EM Disintegrator Charge",
    meta_level: "Level 0"
  },
  "xoru_9": {
    name: "Xoru 9",
    category: "Energy Lance",
    charge_size: "Medium",
    reload_time_s: 0.0,
    mass_kg: 50290,
    activation_cost_gj: 1.8,
    structure_hitpoints_hp: 40,
    turret_tracking: 600,
    volume_m3: 80,
    capacity_m3: 2.4,
    tech_level: "Level 1",
    damage_multiplier_bonus_per_cycle_pct: 20,
    maximum_damage_multiplier_bonus_pct: 330,
    rate_of_fire_s: 4.5,
    optimal_range_km: 39.23,
    charges_per_cycle: 1,
    damage_modifier_x: 1.1,
    used_with_charge_group: "EM Disintegrator Charge",
    meta_level: "Level 0"
  },
  "xoru_7": {
    name: "Xoru 7",
    category: "Energy Lance",
    charge_size: "Medium",
    reload_time_s: 0.0,
    mass_kg: 49190,
    activation_cost_gj: 1.8,
    structure_hitpoints_hp: 40,
    turret_tracking: 600,
    volume_m3: 80,
    capacity_m3: 2.4,
    tech_level: "Level 1",
    damage_multiplier_bonus_per_cycle_pct: 20,
    maximum_damage_multiplier_bonus_pct: 320,
    rate_of_fire_s: 4.5,
    optimal_range_km: 38.65,
    charges_per_cycle: 1,
    damage_modifier_x: 1,
    used_with_charge_group: "EM Disintegrator Charge",
    meta_level: "Level 0"
  },
  "tuho_s": {
    name: "Tuho S",
    category: "Energy Lance",
    charge_size: "Small",
    reload_time_s: 0.0,
    mass_kg: 80000,
    activation_cost_gj: 1.0,
    structure_hitpoints_hp: 40,
    turret_tracking: 600,
    volume_m3: 20,
    capacity_m3: 1.2,
    tech_level: "Level 1",
    damage_multiplier_bonus_per_cycle_pct: 10,
    maximum_damage_multiplier_bonus_pct: 270,
    rate_of_fire_s: 3.5,
    optimal_range_km: 155.0,
    charges_per_cycle: 1,
    damage_modifier_x: 1.2,
    used_with_charge_group: "EM Disintegrator Charge",
    meta_level: "Level 0"
  },
  "tuho_9": {
    name: "Tuho 9",
    category: "Energy Lance",
    charge_size: "Small",
    reload_time_s: 0.0,
    mass_kg: 70000,
    activation_cost_gj: 1.0,
    structure_hitpoints_hp: 40,
    turret_tracking: 600,
    volume_m3: 20,
    capacity_m3: 1.2,
    tech_level: "Level 1",
    damage_multiplier_bonus_per_cycle_pct: 10,
    maximum_damage_multiplier_bonus_pct: 260,
    rate_of_fire_s: 3.5,
    optimal_range_km: 150.0,
    charges_per_cycle: 1,
    damage_modifier_x: 1.1,
    used_with_charge_group: "EM Disintegrator Charge",
    meta_level: "Level 0"
  },
  "tuho_7": {
    name: "Tuho 7",
    category: "Energy Lance",
    charge_size: "Small",
    reload_time_s: 0.0,
    mass_kg: 60000,
    activation_cost_gj: 1.0,
    structure_hitpoints_hp: 40,
    turret_tracking: 600,
    volume_m3: 20,
    capacity_m3: 1.2,
    tech_level: "Level 1",
    damage_multiplier_bonus_per_cycle_pct: 10,
    maximum_damage_multiplier_bonus_pct: 250,
    rate_of_fire_s: 3.0,
    optimal_range_km: 143.75,
    charges_per_cycle: 1,
    damage_modifier_x: 1,
    used_with_charge_group: "EM Disintegrator Charge",
    meta_level: "Level 0"
  },
  "velocity_cd81": {
    name: "Velocity CD81",
    category: "Crude Engines",
    volume_m3: 100,
    mass_kg: 300000,
    warp_fuel_multiplier_x: -0.5,
    capacitor_recharge_gj_s: 3.4,
    can_be_fitted_to: "Frigate, Destroyer"
  },
  "tempo_cd41": {
    name: "Tempo CD41",
    category: "Crude Engines",
    volume_m3: 100,
    mass_kg: 300000,
    warp_fuel_multiplier_x: -0.475,
    capacitor_recharge_gj_s: 2.8,
    can_be_fitted_to: "Frigate, Destroyer"
  },
  "sojourn": {
    name: "Sojourn",
    category: "Hydrogen Engines",
    volume_m3: 50,
    mass_kg: 150000,
    warp_fuel_multiplier_x: -0.55,
    capacitor_recharge_gj_s: 1.2,
    can_be_fitted_to: "Corvette"
  },
  "embark": {
    name: "Embark",
    category: "Hydrogen Engines",
    volume_m3: 50,
    mass_kg: 150000,
    warp_fuel_multiplier_x: -0.6,
    capacitor_recharge_gj_s: 1,
    can_be_fitted_to: "Shuttle"
  },
  "celerity_cd01": {
    name: "Celerity CD01",
    category: "Crude Engines",
    volume_m3: 100,
    mass_kg: 300000,
    warp_fuel_multiplier_x: -0.425,
    capacitor_recharge_gj_s: 2.2,
    can_be_fitted_to: "Frigate, Destroyer"
  },
  "velocity_cd82": {
    name: "Velocity CD82",
    category: "Crude Engines",
    volume_m3: 200,
    mass_kg: 417280,
    warp_fuel_multiplier_x: -0.5,
    capacitor_recharge_gj_s: 8,
    can_be_fitted_to: "Cruiser, Battleship, Combat Battlecruiser"
  },
  "tempo_cd42": {
    name: "Tempo CD42",
    category: "Crude Engines",
    volume_m3: 200,
    mass_kg: 417280,
    warp_fuel_multiplier_x: -0.475,
    capacitor_recharge_gj_s: 6,
    can_be_fitted_to: "Cruiser, Battleship, Combat Battlecruiser"
  },
  "celerity_cd02": {
    name: "Celerity CD02",
    category: "Crude Engines",
    volume_m3: 200,
    mass_kg: 417280,
    warp_fuel_multiplier_x: -0.425,
    capacitor_recharge_gj_s: 4.5,
    can_be_fitted_to: "Cruiser, Battleship, Combat Battlecruiser"
  },
  "tempo_cd43": {
    name: "Tempo CD43",
    category: "Crude Engines",
    volume_m3: 400,
    mass_kg: 834540,
    warp_fuel_multiplier_x: -0.475,
    capacitor_recharge_gj_s: 14,
    can_be_fitted_to: "Combat Battlecruiser, Battleship"
  },
  "celerity_cd03": {
    name: "Celerity CD03",
    category: "Crude Engines",
    volume_m3: 400,
    mass_kg: 834540,
    warp_fuel_multiplier_x: -0.425,
    capacitor_recharge_gj_s: 11.5,
    can_be_fitted_to: "Combat Battlecruiser, Battleship"
  }
};
