import {chromium} from '/home/rawdata/.npm-global/lib/node_modules/openclaw/node_modules/playwright-core/index.mjs';import fs from 'node:fs/promises';import assert from 'node:assert/strict';
const OUT='/home/rawdata/.openclaw-captain/workspace/research/cradleos-casino-slot-identities-20261008',URL=process.env.QA_URL??'http://127.0.0.1:5200/',TAG=process.env.QA_TAG??'preview';const fixtures=JSON.parse(await fs.readFile(OUT+'/fixtures.json','utf8'));const b=await chromium.launch({executablePath:'/home/rawdata/.cache/ms-playwright/chromium-1228/chrome-linux/chrome',args:['--no-sandbox']});const report={checks:[],errors:[],badAssets:[]};
const saved=r=>{const round={id:1,game:r.key,stake:r.stake,payout:r.payout,values:[1,r.frames.length],label:'Saved feature'};return {version:2,balance:1000000-r.stake+r.payout,sequence:1,history:[round],hand:null,table:null,pack:{game:r.key,rounds:[round],slot:{...r,cursor:1}}}};
try{for(const width of [320,390,1440]){const c=await b.newContext({viewport:{width,height:1000},reducedMotion:'reduce'}),p=await c.newPage();p.on('pageerror',e=>report.errors.push(e.message));p.on('response',r=>{if(r.status()>=400&&/\/data\/icons-cycle7-|\/casino\//.test(r.url())&&r.url().startsWith(URL))report.badAssets.push(r.url())});await p.goto(URL+'#/casino');await p.locator('.lounge-game-tile').first().waitFor();for(const [key,r] of Object.entries(fixtures)){await p.evaluate(s=>sessionStorage.setItem('cradleos:casino:practice:v2',JSON.stringify(s)),saved(r));await p.reload();await p.locator('.identity-stage').waitFor();await p.locator('.identity-stage').scrollIntoViewIfNeeded();await p.waitForFunction(()=>!document.querySelector('.identity-stage .identity-symbol-fallback')&&[...document.querySelectorAll('.identity-stage img')].every(i=>i.complete&&i.naturalWidth>0));assert.equal(await p.locator('.identity-stage .identity-symbol-fallback').count(),0);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert.equal(await p.evaluate(()=>document.getAnimations().filter(a=>a.effect?.getTiming().iterations===Infinity).length),0);const clips=await p.locator('.fleet-coin b,.fleet-coin .coin-fraction').evaluateAll(es=>es.filter(e=>{const r=e.getBoundingClientRect(),p=e.parentElement.getBoundingClientRect();return r.left<p.left+.5||r.right>p.right-.5}).map(e=>({text:e.textContent,width:e.getBoundingClientRect().width,parent:e.parentElement.getBoundingClientRect().width})));assert.deepEqual(clips,[],`${width} ${key}`);}
report.checks.push(`${width}: all eight current saved boards, native images loaded, no fallback/overflow, readable token labels, no infinite animation`);await c.close();}
// A native asset error must be recoverable without turning all symbols into the same icon.
for(const fault of ['manifest.json','assets/*.png']){const c=await b.newContext({viewport:{width:320,height:1000},reducedMotion:'reduce'});await c.route(`**/data/icons-cycle7-*/${fault}`,r=>r.abort());const p=await c.newPage();await p.goto(URL+'#/casino');await p.locator('.lounge-game-tile').first().waitFor();await p.evaluate(s=>sessionStorage.setItem('cradleos:casino:practice:v2',JSON.stringify(s)),saved(fixtures.slot_scrapyard));await p.reload();await p.locator('.identity-stage .identity-symbol-fallback').first().waitFor();const cells=await p.locator('.fleet-cell').evaluateAll(es=>es.map(e=>({n:Number(e.dataset.symbol),text:e.innerText})));for(const cell of cells.filter(x=>x.n<7))assert(cell.text.includes(String(cell.n+1).padStart(2,'0')));report.checks.push(`${fault} blocked: visible per-symbol codes/names survive`);await c.close();}
// Sound is opt-in, remains on during spins, closes every active context on mute/visibility.
{const c=await b.newContext({viewport:{width:390,height:1000}}),p=await c.newPage();await p.addInitScript(()=>{const O=window.AudioContext;window.__audio=[];window.AudioContext=class extends O{constructor(...args){super(...args);window.__audio.push(this)}}});await p.goto(URL+'#/casino');await p.locator('.lounge-game-tile').first().waitFor();assert.equal(await p.evaluate(()=>window.__audio.length),0);await p.getByRole('button',{name:'Enable casino sound',exact:true}).click();assert(await p.evaluate(()=>window.__audio.at(-1).state==='running'));await p.getByRole('button',{name:'Mute casino sound',exact:true}).click();assert(await p.evaluate(()=>window.__audio.every(c=>c.state==='closed')));await p.getByRole('button',{name:'Enable casino sound',exact:true}).click();await p.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'))});assert(await p.evaluate(()=>window.__audio.every(c=>c.state==='closed')));report.checks.push('No initial audio; opt-in opens context; mute/hidden closes all voices');await c.close();}
assert.deepEqual(report.errors,[]);assert.deepEqual(report.badAssets,[]);console.log(report.checks.join('\n'));await fs.writeFile(`${OUT}/${TAG}-presentation.json`,JSON.stringify(report,null,2));}finally{await b.close()}
