import { chromium } from '/home/rawdata/.npm-global/lib/node_modules/openclaw/node_modules/playwright-core/index.mjs';
import { writeFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const base=process.env.QA_BASE??'http://127.0.0.1:5220',tag=process.env.QA_TAG??'preview',live=base.startsWith('https:'),out=new URL('./',import.meta.url).pathname,KEY='cradleos:casino:practice:v2';
const report={base,scope:'Actual app, natural RNG, isolated browser-local Play Money; viewport-emulated Chromium; no wallet',checks:[],errors:[]};
const b=await chromium.launch({executablePath:'/home/rawdata/.cache/ms-playwright/chromium-1228/chrome-linux/chrome',args:['--no-sandbox','--no-proxy-server']});
const read=p=>p.evaluate(k=>JSON.parse(sessionStorage.getItem(k)),KEY);
async function init(width,reduce=false){const c=await b.newContext({viewport:{width,height:900},reducedMotion:reduce?'reduce':'no-preference'}),p=await c.newPage();p.on('pageerror',e=>report.errors.push(e.message));await p.goto(base+'/#/casino');await p.locator('.lounge-game-tile').filter({hasText:'Deep Scan'}).click();await p.locator('.keno-scanner').waitFor();assert.equal(await p.locator('.scan-result-ping').count(),0);return{c,p};}
async function observe(p){await p.evaluate(()=>{window.deepFrames=[];window.deepStop=false;function tick(){const board=document.querySelector('.keno-scanner');if(board){const t=+board.dataset.progress,pings=[...board.querySelectorAll('.scan-result-ping')].map(svg=>{const r=svg.parentElement.getBoundingClientRect(),circle=svg.querySelector('circle'),pt=new DOMPoint(50,50).matrixTransform(circle.getScreenCTM());return{value:+svg.dataset.scanPing,phase:+svg.dataset.phase,r:+circle.getAttribute('r'),opacity:+circle.getAttribute('opacity'),color:getComputedStyle(svg).color,centerError:Math.hypot(pt.x-r.x-r.width/2,pt.y-r.y-r.height/2),drawn:svg.parentElement.dataset.drawn==='true',matched:svg.parentElement.classList.contains('picked')};});window.deepFrames.push({t,pings,drawn:[...board.querySelectorAll('[data-drawn="true"]')].map(e=>+e.dataset.number)});}if(!window.deepStop)requestAnimationFrame(tick)}requestAnimationFrame(tick);});}
async function idle(p){await p.waitForFunction(()=>!document.querySelector('.round-active'));}
try{
for(const width of live?[390,1440]:[320,390,1440]){const {c,p}=await init(width,width===1440);assert.equal(await p.getByRole('combobox',{name:'Game animation'}).inputValue(),'animated');await observe(p);await p.locator('.lounge-start').click();const paid=await read(p),round=paid.pack.rounds[0],n=round.values[0],picks=round.values.slice(1,n+1),drawn=round.values.slice(n+1);await p.waitForTimeout(650);await p.locator('.keno-scanner').screenshot({path:out+`${tag}-${width}-motion.png`});await idle(p);await p.evaluate(()=>window.deepStop=true);const frames=await p.evaluate(()=>window.deepFrames),active=frames.filter(f=>f.t<1);assert(active.length>25);const hits=drawn.map((value,index)=>{const samples=active.flatMap(f=>f.pings.filter(x=>x.value===value).map(x=>({...x,t:f.t})));assert(samples.length>=3,`ping ${value} was visible`);assert(samples.every(x=>x.drawn&&x.t>=(index+1)/11&&x.centerError<.6));assert(samples.at(-1).r>samples[0].r+10);assert(samples.at(-1).opacity<samples[0].opacity);assert(samples.every(x=>x.matched===picks.includes(value)));return{value,index,samples:samples.length,first:samples[0],last:samples.at(-1)};});for(const f of active){assert.deepEqual(f.drawn.slice().sort((a,b)=>a-b),drawn.slice(0,Math.min(10,Math.floor(f.t*11))).sort((a,b)=>a-b));assert(f.pings.length<=1)}assert(active.some(f=>f.t>.999&&f.pings.length===0)||frames.some(f=>f.t===1&&f.pings.length===0));assert.deepEqual(await p.locator('[data-drawn="true"]').evaluateAll(es=>es.map(e=>+e.dataset.number)),drawn.slice().sort((a,b)=>a-b));assert.equal(await p.locator('.scan-result-ping,.scanner-sweep').count(),0);assert.deepEqual(await read(p),paid);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.locator('.keno-scanner').screenshot({path:out+`${tag}-${width}-result.png`});report.checks.push({width,drawn,picks,pings:hits,ledgerUnchanged:true,finalPingComplete:true});console.log(width,'10 pings PASS');await c.close();}
if(!live)for(const boundary of ['instant','system','hidden','resize','reload','tickets']){const {c,p}=await init(390,boundary==='system');if(['instant','system'].includes(boundary))await p.getByRole('combobox',{name:'Game animation'}).selectOption(boundary);if(boundary==='tickets')await p.getByRole('button',{name:'＋ Ticket',exact:true}).click();await p.locator('.lounge-start').click();const paid=await read(p);await p.waitForTimeout(420);if(boundary==='hidden')await p.evaluate(()=>{Object.defineProperty(document,'hidden',{value:true,configurable:true});document.dispatchEvent(new Event('visibilitychange'))});if(boundary==='resize')await p.setViewportSize({width:320,height:900});if(boundary==='reload')await p.reload();if(boundary==='tickets'){const controls=p.getByRole('group',{name:'View ticket result'});await controls.getByRole('button').nth(1).click();assert.equal(paid.pack.rounds.length,2);assert.deepEqual(paid.pack.rounds[0].values.slice(-10),paid.pack.rounds[1].values.slice(-10));await controls.getByRole('button').nth(0).click();}if(['instant','system','hidden','reload'].includes(boundary)){assert.equal(await p.locator('.scan-result-ping').count(),0);assert.equal(await p.locator('[data-drawn="true"]').count(),10);}await idle(p);assert.equal(await p.locator('.scan-result-ping').count(),0);assert.deepEqual(await read(p),paid);report.checks.push({boundary,ok:true,ledgerUnchanged:true});console.log(boundary,'PASS');await c.close();}
assert.deepEqual(report.errors,[]);
}catch(e){report.failure=String(e);throw e}finally{await b.close();await writeFile(out+tag+'-browser.json',JSON.stringify(report,null,2)+'\n');}
