import {chromium} from '/home/rawdata/.npm-global/lib/node_modules/openclaw/node_modules/playwright-core/index.mjs';
import {readFile,writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const base=process.env.QA_BASE??'http://127.0.0.1:5223',tag=process.env.QA_TAG??'preview',live=base.startsWith('https:'),out=new URL('./',import.meta.url).pathname,KEY='cradleos:casino:practice:v2',fixtures=JSON.parse(await readFile(out+'fixtures.json','utf8'));
const report={base,scope:live?'Actual app; isolated browser-local free Play Money; fresh natural RNG successes/losses; viewport emulation; no wallet':'Actual app; isolated browser-local free Play Money; fresh natural RNG successes/losses, engine-produced saved boundaries and lifecycle; viewport emulation; no wallet',checks:[],errors:[],assetFailures:[]};
const b=await chromium.launch({executablePath:'/home/rawdata/.cache/ms-playwright/chromium-1228/chrome-linux/chrome',args:['--no-sandbox','--no-proxy-server']});
const read=p=>p.evaluate(k=>JSON.parse(sessionStorage.getItem(k)),KEY),idle=p=>p.waitForFunction(()=>!document.querySelector('.round-active'));
async function init(width,reduce=false){const c=await b.newContext({viewport:{width,height:950},reducedMotion:reduce?'reduce':'no-preference'}),p=await c.newPage();p.on('pageerror',e=>report.errors.push(e.message));p.on('response',r=>{if(r.status()>=400&&r.url().includes('/casino/lai-jump/'))report.assetFailures.push(r.url())});await p.goto(base+'/#/casino');await p.locator('.lounge-game-tile').filter({hasText:'Warp Run'}).click();await p.locator('.warp-run-stage').waitFor();return{c,p};}
async function observe(p){await p.evaluate(()=>{window.warpFrames=[];window.warpStop=false;function tick(){const e=document.querySelector('.warp-run-stage'),ship=e?.querySelector('.warp-hull');if(e&&ship){const shape=ship.querySelector('image').getBoundingClientRect();window.warpFrames.push({t:+e.dataset.progress,phase:e.dataset.phase,ship:ship.getAttribute('transform'),worldX:+ship.dataset.worldX,cameraX:+ship.dataset.cameraX,velocity:+ship.dataset.velocity,opacity:+ship.getAttribute('opacity'),thrust:+e.querySelector('.warp-exhaust').getAttribute('opacity'),width:shape.width,height:shape.height,paid:e.querySelector('[data-paid]').dataset.paid==='true',multiplier:e.querySelector('.warp-readouts strong').textContent,stars:[...e.querySelectorAll('.warp-stars circle')].map(n=>+n.getAttribute('cx')),debris:[...e.querySelectorAll('.warp-fragment')].map(n=>n.getAttribute('transform')),flash:!!e.querySelector('.warp-flash'),wake:!!e.querySelector('.warp-wake')});}if(!window.warpStop)requestAnimationFrame(tick)}requestAnimationFrame(tick)});}
async function settled(p,round){const win=round.values[0]>=round.values[1];assert.equal(await p.locator('.warp-run-stage').getAttribute('data-phase'),win?'warped':'ended');assert.equal(await p.locator('[data-paid]').getAttribute('data-paid'),String(win));assert.equal(await p.locator('.warp-flash,.warp-wake').count(),0);assert.equal(await p.locator('.warp-fragment').count(),win?0:9);assert.equal(await p.locator('.warp-hull').getAttribute('opacity'),'0');assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}
try{
for(const width of live?[390,1440]:[320,390,1440]){const {c,p}=await init(width,width===1440);assert.equal(await p.getByRole('combobox',{name:'Game animation'}).inputValue(),'animated');const seen=new Set();for(let attempt=0;attempt<8&&seen.size<2;attempt++){await p.getByRole('spinbutton',{name:'Target multiplier'}).fill(seen.has('paid')?'1000':'1.01');await observe(p);await p.locator('.lounge-start').click();const committed=await read(p),r=committed.history[0],win=r.values[0]>=r.values[1],outcome=win?'paid':'missed';for(const at of [.04,.12,.22,.4,.75,.88]){await p.waitForFunction(t=>+document.querySelector('.warp-run-stage').dataset.progress>=t,at);await p.locator('.warp-run-stage').screenshot({path:out+`${tag}-${width}-${outcome}-${at}.png`});}await idle(p);await p.evaluate(()=>window.warpStop=true);const frames=await p.evaluate(()=>window.warpFrames),active=frames.filter(f=>f.t>0&&f.t<1);assert(active.length>60);assert(active.every(f=>!(/rotate|scale/.test(f.ship))));assert(active.every(f=>Math.abs(f.width-active[0].width)<.1&&Math.abs(f.height-active[0].height)<.1));assert(frames.every(f=>JSON.stringify(f.stars)===JSON.stringify(frames[0].stars)));for(const f of active){const cross=win?Math.log(r.values[1]/10000)/Math.log(r.values[0]/10000):Infinity;assert.equal(f.paid,win&&(f.t>=.74||f.t/.74>=cross));}
if(win){assert(active.every(f=>f.phase!=='ended'&&!f.flash&&f.debris.length===0));const warp=active.filter(f=>f.phase==='warping');assert(warp.length>8);assert(warp.at(-1).worldX>warp[0].worldX+250);assert(warp.at(-1).velocity>warp[0].velocity);assert(warp.every(f=>f.opacity===1&&f.thrust===1));const escaped=active.filter(f=>f.phase==='warped');assert(escaped.length>3);assert(escaped.every(f=>f.opacity===0&&f.thrust===0));}else{const flight=active.filter(f=>f.t<.74),breakup=active.filter(f=>f.t>=.74);assert(flight.every(f=>f.phase==='flight'&&f.opacity===1&&f.debris.length===0));assert(breakup.every(f=>f.phase==='ended'&&f.opacity===0&&f.thrust===0&&f.debris.length===9));assert(breakup.some(f=>f.flash));assert.notDeepEqual(breakup[0].debris,breakup.at(-1).debris);}
await settled(p,r);assert.deepEqual(await read(p),committed);const framing=await p.locator('.warp-run-stage').evaluate(e=>{const r=e.getBoundingClientRect();return{height:r.height,visible:Math.max(0,Math.min(innerHeight,r.bottom)-Math.max(64,r.top))}});assert(framing.visible>=framing.height*.97);report.checks.push({width,outcome,values:r.values,framing,frameCount:frames.length,samples:frames.filter((f,i)=>i%10===0||i===frames.length-1),ledgerUnchanged:true});console.log(width,outcome,'PASS');seen.add(outcome);}assert.equal(seen.size,2);await c.close();}
if(!live){for(const [name,saved] of Object.entries(fixtures)){const {c,p}=await init(320);await p.evaluate(([k,s])=>sessionStorage.setItem(k,JSON.stringify(s)),[KEY,saved]);await p.reload();await p.locator('.warp-run-stage').waitFor();assert.equal(await p.locator('.round-active').count(),0);await settled(p,saved.history[0]);if(name==='nearMiss')assert.equal(await p.locator('.warp-readouts strong').innerText(),'1.9999×');assert.deepEqual(await read(p),saved);report.checks.push({saved:name,values:saved.history[0].values,ledgerUnchanged:true});console.log('saved',name,'PASS');await c.close();}
for(const boundary of ['instant','system','hidden','resize','reload']){const {c,p}=await init(390,boundary==='system');if(['instant','system'].includes(boundary))await p.getByRole('combobox',{name:'Game animation'}).selectOption(boundary);await p.getByRole('spinbutton',{name:'Target multiplier'}).fill('1.01');await p.locator('.lounge-start').click();const committed=await read(p);await p.waitForTimeout(200);if(boundary==='hidden')await p.evaluate(()=>{Object.defineProperty(document,'hidden',{value:true,configurable:true});document.dispatchEvent(new Event('visibilitychange'))});if(boundary==='resize')await p.setViewportSize({width:320,height:950});if(boundary==='reload')await p.reload();await p.locator('.warp-run-stage').waitFor();if(boundary!=='resize')await settled(p,committed.history[0]);await idle(p);await settled(p,committed.history[0]);assert.deepEqual(await read(p),committed);report.checks.push({boundary,values:committed.history[0].values,ledgerUnchanged:true});console.log(boundary,'PASS');await c.close();}}
assert.deepEqual(report.errors,[]);assert.deepEqual(report.assetFailures,[]);
}catch(e){report.failure=String(e);throw e}finally{await b.close();await writeFile(out+tag+'-browser.json',JSON.stringify(report,null,2)+'\n');}
