import {chromium} from '/home/rawdata/.npm-global/lib/node_modules/openclaw/node_modules/playwright-core/index.mjs';
import {readFile,writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const base=process.env.QA_BASE??'http://127.0.0.1:5218',tag=process.env.QA_TAG??'development',live=base.startsWith('https:'),out=new URL('./',import.meta.url).pathname,profiles=JSON.parse(await readFile(out+'profiles.json','utf8')),report={base,mode:'Actual app decorative asset, label and audio-control checks; no listening claim',checks:[],errors:[]};
const b=await chromium.launch({executablePath:'/home/rawdata/.cache/ms-playwright/chromium-1228/chrome-linux/chrome',args:['--no-sandbox','--no-proxy-server']});
async function init(width,fail=false){const c=await b.newContext({viewport:{width,height:844}}),p=await c.newPage();p.on('pageerror',e=>report.errors.push(e.message));if(fail)await p.route('**/icons-cycle7-*/manifest.json',r=>r.abort());await p.goto(base+'/#/casino');await p.locator('.lounge-game-tile').filter({hasText:'Plinko'}).click();await p.locator('.plinko-feeder').waitFor();return{c,p};}
try{
for(const width of (live?[320,1440]:[320,390,1440])){const {c,p}=await init(width);for(const [profile,pay] of Object.entries(profiles)){if(live&&!['Classic','High'].includes(profile))continue;await p.getByRole('button',{name:profile,exact:true}).click();const labels=await p.locator('.plinko-bay-label').evaluateAll(es=>es.map(e=>({text:e.textContent,x:+e.getAttribute('x'),box:{x:e.getBBox().x,y:e.getBBox().y,w:e.getBBox().width,h:e.getBBox().height}})));assert.deepEqual(labels.map(x=>x.text),pay.map(x=>`${x/10000}×`));for(let i=0;i<13;i++){assert.equal(labels[i].x,42+18*i);assert(labels[i].box.w<32);for(let j=i+1;j<13;j++){const a=labels[i].box,z=labels[j].box;assert(a.x+a.w<=z.x||z.x+z.w<=a.x||a.y+a.h<=z.y||z.y+z.h<=a.y,'labels do not overlap')}}await p.locator('.lounge-surface').evaluate(e=>scrollTo(0,scrollY+e.getBoundingClientRect().top-64));await p.locator('.lounge-plinko').screenshot({path:out+`${tag}-${width}-${profile}-labels.png`});report.checks.push({width,profile,labels});}assert.equal(await p.locator('.plinko-client-mark').count(),2);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await c.close();}
if(!live){const {c,p}=await init(390,true);assert.equal(await p.locator('.plinko-client-mark').count(),0);await p.locator('.lounge-start').click();await p.waitForFunction(()=>!document.querySelector('.round-active'));assert.equal(await p.locator('.plinko-ball').count(),1);report.checks.push({missingManifest:'board and drop remain functional'});await c.close();}
if(!live){const {c,p}=await init(390);await p.evaluate(()=>{window.audioProbe={contexts:0,hz:[]};const Original=window.AudioContext;window.AudioContext=class extends Original{constructor(...args){super(...args);window.audioProbe.contexts++}createOscillator(){const o=super.createOscillator(),set=o.frequency.setValueAtTime.bind(o.frequency);o.frequency.setValueAtTime=(v,t)=>{window.audioProbe.hz.push(v);return set(v,t)};return o}}});await p.locator('.lounge-start').click();await p.waitForFunction(()=>!document.querySelector('.round-active'));assert.deepEqual(await p.evaluate(()=>window.audioProbe),{contexts:0,hz:[]});await p.getByRole('button',{name:'Enable casino sound'}).click();await p.locator('.lounge-start').click();await p.waitForFunction(()=>!document.querySelector('.round-active'));const audio=await p.evaluate(()=>window.audioProbe);assert(audio.hz.some(x=>x===1260||x===720));assert(audio.hz.includes(190));await p.getByRole('button',{name:'Mute casino sound'}).click();const n=audio.hz.length;await p.locator('.lounge-start').click();await p.waitForFunction(()=>!document.querySelector('.round-active'));assert.equal(await p.evaluate(()=>window.audioProbe.hz.length),n);report.checks.push({audio:'silent by default; dedicated impacts/catch after opt-in; mute stops notes',observedHz:[...new Set(audio.hz)]});await c.close();}
assert.deepEqual(report.errors,[]);
}catch(e){report.failure=String(e);throw e}finally{await b.close();await writeFile(out+tag+'-rig-checks.json',JSON.stringify(report,null,2));}
